/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.model;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;

/**
 * @author Fujitsu
 *
 */
public class DashBoardInfo implements Serializable{
	private Integer totalProject;
	private Integer totalTask;
	private Integer totalGoal;
	private Integer totalTeam;
	private Integer completedProject;
	private Integer dueProjet;
	private Integer inprogressProject;
	private Integer completedTask;
	private Integer dueTask;
	private Integer inprogressTask;
	
	private Integer completedGoals;
	private Integer dueGoals;
	private Integer inprogressGoals;
	private List<EmProject> projectList;	
	private List<EmTask> taskList;
	private List<EmTeam> teamList;
	private List<EmGoal> goalList;
	private HashMap<String,Integer> ratingCount;
	/**
	 * @return the totalProject
	 */
	public Integer getTotalProject() {
		return totalProject;
	}
	/**
	 * @param totalProject the totalProject to set
	 */
	public void setTotalProject(Integer totalProject) {
		this.totalProject = totalProject;
	}
	/**
	 * @return the totalTask
	 */
	public Integer getTotalTask() {
		return totalTask;
	}
	/**
	 * @param totalTask the totalTask to set
	 */
	public void setTotalTask(Integer totalTask) {
		this.totalTask = totalTask;
	}
	/**
	 * @return the totalGoal
	 */
	public Integer getTotalGoal() {
		return totalGoal;
	}
	/**
	 * @param totalGoal the totalGoal to set
	 */
	public void setTotalGoal(Integer totalGoal) {
		this.totalGoal = totalGoal;
	}
	/**
	 * @return the totalTeam
	 */
	public Integer getTotalTeam() {
		return totalTeam;
	}
	/**
	 * @param totalTeam the totalTeam to set
	 */
	public void setTotalTeam(Integer totalTeam) {
		this.totalTeam = totalTeam;
	}
	/**
	 * @return the completedProject
	 */
	public Integer getCompletedProject() {
		return completedProject;
	}
	/**
	 * @param completedProject the completedProject to set
	 */
	public void setCompletedProject(Integer completedProject) {
		this.completedProject = completedProject;
	}
	/**
	 * @return the dueProjet
	 */
	public Integer getDueProjet() {
		return dueProjet;
	}
	/**
	 * @param dueProjet the dueProjet to set
	 */
	public void setDueProjet(Integer dueProjet) {
		this.dueProjet = dueProjet;
	}
	/**
	 * @return the inprogressProject
	 */
	public Integer getInprogressProject() {
		return inprogressProject;
	}
	/**
	 * @param inprogressProject the inprogressProject to set
	 */
	public void setInprogressProject(Integer inprogressProject) {
		this.inprogressProject = inprogressProject;
	}
	/**
	 * @return the projectList
	 */
	public List<EmProject> getProjectList() {
		return projectList;
	}
	/**
	 * @param projectList the projectList to set
	 */
	public void setProjectList(List<EmProject> projectList) {
		this.projectList = projectList;
	}
	/**
	 * @return the taskList
	 */
	public List<EmTask> getTaskList() {
		return taskList;
	}
	/**
	 * @param taskList the taskList to set
	 */
	public void setTaskList(List<EmTask> taskList) {
		this.taskList = taskList;
	}
	/**
	 * @return the teamList
	 */
	public List<EmTeam> getTeamList() {
		return teamList;
	}
	/**
	 * @param teamList the teamList to set
	 */
	public void setTeamList(List<EmTeam> teamList) {
		this.teamList = teamList;
	}
	/**
	 * @return the goalList
	 */
	public List<EmGoal> getGoalList() {
		return goalList;
	}
	/**
	 * @param goalList the goalList to set
	 */
	public void setGoalList(List<EmGoal> goalList) {
		this.goalList = goalList;
	}
	/**
	 * @return the completedTask
	 */
	public Integer getCompletedTask() {
		return completedTask;
	}
	/**
	 * @param completedTask the completedTask to set
	 */
	public void setCompletedTask(Integer completedTask) {
		this.completedTask = completedTask;
	}
	/**
	 * @return the dueTask
	 */
	public Integer getDueTask() {
		return dueTask;
	}
	/**
	 * @param dueTask the dueTask to set
	 */
	public void setDueTask(Integer dueTask) {
		this.dueTask = dueTask;
	}
	/**
	 * @return the inprogressTask
	 */
	public Integer getInprogressTask() {
		return inprogressTask;
	}
	/**
	 * @param inprogressTask the inprogressTask to set
	 */
	public void setInprogressTask(Integer inprogressTask) {
		this.inprogressTask = inprogressTask;
	}
	/**
	 * @return the completedGoals
	 */
	public Integer getCompletedGoals() {
		return completedGoals;
	}
	/**
	 * @param completedGoals the completedGoals to set
	 */
	public void setCompletedGoals(Integer completedGoals) {
		this.completedGoals = completedGoals;
	}
	/**
	 * @return the dueGols
	 */
	public Integer getDueGoals() {
		return dueGoals;
	}
	/**
	 * @param dueGols the dueGols to set
	 */
	public void setDueGoals(Integer dueGoals) {
		this.dueGoals = dueGoals;
	}
	/**
	 * @return the inprogressGoals
	 */
	public Integer getInprogressGoals() {
		return inprogressGoals;
	}
	/**
	 * @param inprogressGoals the inprogressGoals to set
	 */
	public void setInprogressGoals(Integer inprogressGoals) {
		this.inprogressGoals = inprogressGoals;
	}
	/**
	 * @return the ratingCount
	 */
	public HashMap<String, Integer> getRatingCount() {
		return ratingCount;
	}
	/**
	 * @param ratingCount the ratingCount to set
	 */
	public void setRatingCount(HashMap<String, Integer> ratingCount) {
		this.ratingCount = ratingCount;
	}

}
