/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

import com.sun.istack.internal.NotNull;

/**
 * @author Fujitsu
 *
 */
@Entity
@Table(name = "evaluate_Performance_master")
@XmlRootElement
public class EmployeePerformanceMaster implements Serializable {

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "performance_mst_id")
    private Integer performaceMstId;
	@Column(name = "performance_period_id")
	private Integer performancePeriodId;
    @Column(name = "employee_id")
    private Integer employeeId;
    @Column(name = "evaluater_id")
    private Integer evaluaterId;
    
    @Column(name = "goal_id")
    private Integer goalId;
    @Column(name = "task_id")
    private Integer taskId;
    @Column(name = "project_id")
    private Integer projectId;
    @Column(name = "rating")
    private Integer rating;
    @Column(name = "comment")
    private String comment;
    
   
   
  
    @Column(name = "created_date")
    @Temporal(TemporalType.DATE)
    private Date createdDate;
    @Column(name = "updated_date")
    @Temporal(TemporalType.DATE)
    private Date updatedDate;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 5)
    @Column(name = "activate_flag")
    private Integer activateFlag;
	/**
	 * @return the performaceMstId
	 */
	public Integer getPerformaceMstId() {
		return performaceMstId;
	}
	/**
	 * @param performaceMstId the performaceMstId to set
	 */
	public void setPerformaceMstId(Integer performaceMstId) {
		this.performaceMstId = performaceMstId;
	}
	/**
	 * @return the employeeId
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}
	/**
	 * @param employeeId the employeeId to set
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}
	/**
	 * @return the evaluaterId
	 */
	public Integer getEvaluaterId() {
		return evaluaterId;
	}
	/**
	 * @param evaluaterId the evaluaterId to set
	 */
	public void setEvaluaterId(Integer evaluaterId) {
		this.evaluaterId = evaluaterId;
	}
	/**
	 * @return the goalId
	 */
	public Integer getGoalId() {
		return goalId;
	}
	/**
	 * @param goalId the goalId to set
	 */
	public void setGoalId(Integer goalId) {
		this.goalId = goalId;
	}
	/**
	 * @return the taskId
	 */
	public Integer getTaskId() {
		return taskId;
	}
	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}
	/**
	 * @return the projectId
	 */
	public Integer getProjectId() {
		return projectId;
	}
	/**
	 * @param projectId the projectId to set
	 */
	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}
	/**
	 * @return the rating
	 */
	public Integer getRating() {
		return rating;
	}
	/**
	 * @param rating the rating to set
	 */
	public void setRating(Integer rating) {
		this.rating = rating;
	}
	/**
	 * @return the comment
	 */
	public String getComment() {
		return comment;
	}
	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}
	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}
	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	/**
	 * @return the activateFlag
	 */
	public Integer getActivateFlag() {
		return activateFlag;
	}
	/**
	 * @param activateFlag the activateFlag to set
	 */
	public void setActivateFlag(Integer activateFlag) {
		this.activateFlag = activateFlag;
	}
	/**
	 * @return the performancePeriodId
	 */
	public Integer getPerformancePeriodId() {
		return performancePeriodId;
	}
	/**
	 * @param performancePeriodId the performancePeriodId to set
	 */
	public void setPerformancePeriodId(Integer performancePeriodId) {
		this.performancePeriodId = performancePeriodId;
	} 
}
