/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.model;

import java.io.Serializable;
import java.util.List;

/**
 * @author Fujitsu
 *
 */
public class EmployeeTaskInfo implements Serializable {
	private EmTask  task;
	private List<EmployeeTaskMpg>  employeeTaskMpg;

}
