/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * @author Fujitsu
 *
 */
@Entity
@Table(name = "employee_task_mpg")
public class EmployeeTaskMpg implements Serializable {
		@Id
	    @GeneratedValue(strategy = GenerationType.IDENTITY)
	    @Basic(optional = false)
	    @Column(name = "employee_task_id")
	    private Integer employeeTaskId;
	    @Basic(optional = false)
	    @NotNull
	    @Column(name = "task_id")
	    private Integer taskId;
	    @Basic(optional = false)
	    @NotNull
	    @Column(name = "employee_id")
	    private Integer employeeId;
	    @Column(name = "created_date")
	    @Temporal(TemporalType.DATE)
	    private Date createdDate;
	    @Column(name = "updated_date")
	    @Temporal(TemporalType.DATE)
	    private Date updatedDate;
	    @Column(name = "activate_flag")
	    private Integer activateFlag;
	    
	    @Column(name = "comment")
	    private String comment;
	    @Column(name = "reply")
	    private String reply;
	    @Column(name = "completion_date")
	    @Temporal(TemporalType.DATE)
	    private Date completionDate;
	    @Column(name = "employee_task_status")
	    private String employeeTaskStatus;
	    @Column(name = "assigned_by_id")
	    private Integer assignedById;
		/**
		 * @return the employeeTaskId
		 */
		public Integer getEmployeeTaskId() {
			return employeeTaskId;
		}
		/**
		 * @param employeeTaskId the employeeTaskId to set
		 */
		public void setEmployeeTaskId(Integer employeeTaskId) {
			this.employeeTaskId = employeeTaskId;
		}
		/**
		 * @return the taskId
		 */
		public Integer getTaskId() {
			return taskId;
		}
		/**
		 * @param taskId the taskId to set
		 */
		public void setTaskId(Integer taskId) {
			this.taskId = taskId;
		}
		/**
		 * @return the employeeId
		 */
		public Integer getEmployeeId() {
			return employeeId;
		}
		/**
		 * @param employeeId the employeeId to set
		 */
		public void setEmployeeId(Integer employeeId) {
			this.employeeId = employeeId;
		}
		/**
		 * @return the createdDate
		 */
		public Date getCreatedDate() {
			return createdDate;
		}
		/**
		 * @param createdDate the createdDate to set
		 */
		public void setCreatedDate(Date createdDate) {
			this.createdDate = createdDate;
		}
		/**
		 * @return the updatedDate
		 */
		public Date getUpdatedDate() {
			return updatedDate;
		}
		/**
		 * @param updatedDate the updatedDate to set
		 */
		public void setUpdatedDate(Date updatedDate) {
			this.updatedDate = updatedDate;
		}
		/**
		 * @return the activateFlag
		 */
		public Integer getActivateFlag() {
			return activateFlag;
		}
		/**
		 * @param activateFlag the activateFlag to set
		 */
		public void setActivateFlag(Integer activateFlag) {
			this.activateFlag = activateFlag;
		}
		/**
		 * @return the comment
		 */
		public String getComment() {
			return comment;
		}
		/**
		 * @param comment the comment to set
		 */
		public void setComment(String comment) {
			this.comment = comment;
		}
		/**
		 * @return the reply
		 */
		public String getReply() {
			return reply;
		}
		/**
		 * @param reply the reply to set
		 */
		public void setReply(String reply) {
			this.reply = reply;
		}
		/**
		 * @return the completionDate
		 */
		public Date getCompletionDate() {
			return completionDate;
		}
		/**
		 * @param completionDate the completionDate to set
		 */
		public void setCompletionDate(Date completionDate) {
			this.completionDate = completionDate;
		}
		/**
		 * @return the employeeTaskStatus
		 */
		public String getEmployeeTaskStatus() {
			return employeeTaskStatus;
		}
		/**
		 * @param employeeTaskStatus the employeeTaskStatus to set
		 */
		public void setEmployeeTaskStatus(String employeeTaskStatus) {
			this.employeeTaskStatus = employeeTaskStatus;
		}
		/**
		 * @return the assignedById
		 */
		public Integer getAssignedById() {
			return assignedById;
		}
		/**
		 * @param assignedById the assignedById to set
		 */
		public void setAssignedById(Integer assignedById) {
			this.assignedById = assignedById;
		}

}
