/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.model;

/**
 * @author Fujitsu
 *
 */
public class ExitInterviewEmployeeResponseView {
	private Integer departmentId;
    private String departmentName;
    private String employeeFname;
    private String employeeMname;
    private Integer designationId;
    private String designationName;
    private String employeeEmail;
    private String employeeProfileImg;
    private Long responseId;
	/**
	 * @return the departmentId
	 */
	public Integer getDepartmentId() {
		return departmentId;
	}
	/**
	 * @param departmentId the departmentId to set
	 */
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}
	/**
	 * @return the departmentName
	 */
	public String getDepartmentName() {
		return departmentName;
	}
	/**
	 * @param departmentName the departmentName to set
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}
	/**
	 * @return the employeeFname
	 */
	public String getEmployeeFname() {
		return employeeFname;
	}
	/**
	 * @param employeeFname the employeeFname to set
	 */
	public void setEmployeeFname(String employeeFname) {
		this.employeeFname = employeeFname;
	}
	/**
	 * @return the employeeMname
	 */
	public String getEmployeeMname() {
		return employeeMname;
	}
	/**
	 * @param employeeMname the employeeMname to set
	 */
	public void setEmployeeMname(String employeeMname) {
		this.employeeMname = employeeMname;
	}
	/**
	 * @return the designationId
	 */
	public Integer getDesignationId() {
		return designationId;
	}
	/**
	 * @param designationId the designationId to set
	 */
	public void setDesignationId(Integer designationId) {
		this.designationId = designationId;
	}
	/**
	 * @return the designationName
	 */
	public String getDesignationName() {
		return designationName;
	}
	/**
	 * @param designationName the designationName to set
	 */
	public void setDesignationName(String designationName) {
		this.designationName = designationName;
	}
	/**
	 * @return the employeeEmail
	 */
	public String getEmployeeEmail() {
		return employeeEmail;
	}
	/**
	 * @param employeeEmail the employeeEmail to set
	 */
	public void setEmployeeEmail(String employeeEmail) {
		this.employeeEmail = employeeEmail;
	}
	/**
	 * @param departmentId
	 * @param departmentName
	 * @param employeeFname
	 * @param employeeMname
	 * @param designationId
	 * @param designationName
	 * @param employeeEmail
	 */
	public ExitInterviewEmployeeResponseView(Integer departmentId, String departmentName, String employeeFname,
			String employeeMname, Integer designationId, String designationName, 
			String employeeEmail,String employeeProfileImg,Long responseId) {
		super();
		this.departmentId = departmentId;
		this.departmentName = departmentName;
		this.employeeFname = employeeFname;
		this.employeeMname = employeeMname;
		this.designationId = designationId;
		this.designationName = designationName;
		this.employeeEmail = employeeEmail;
		this.employeeProfileImg=employeeProfileImg;
		this.responseId=responseId;
	}
	/**
	 * @return the employeeProfileImg
	 */
	public String getEmployeeProfileImg() {
		return employeeProfileImg;
	}
	/**
	 * @param employeeProfileImg the employeeProfileImg to set
	 */
	public void setEmployeeProfileImg(String employeeProfileImg) {
		this.employeeProfileImg = employeeProfileImg;
	}
	public ExitInterviewEmployeeResponseView()
	{
		
	}
	/**
	 * @return the responseId
	 */
	public Long getResponseId() {
		return responseId;
	}
	/**
	 * @param responseId the responseId to set
	 */
	public void setResponseId(Long responseId) {
		this.responseId = responseId;
	}

}
