/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

import com.sun.istack.internal.NotNull;

/**
 * @author Fujitsu
 *
 */
@Entity
@Table(name = "Exit_Interview_Response_mpg")
@XmlRootElement
public class ExitInterviewResponseMpg implements Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "response_mpg_id")
	private Long responseMpgId;
	@Column(name = "response_id")
	private Long responseId;
	@Column(name = "param_Id")
	private Long paramId;
	@Column(name = "param_rlt_Id")
	private Long paramRltId;
	@Column(name = "created_date")
	@Temporal(TemporalType.DATE)
	private Date createdDate;
	@Column(name = "updated_date")
	@Temporal(TemporalType.DATE)
	private Date updatedDate;
	@Basic(optional = false)
	@NotNull
	@Size(min = 1, max = 5)
	@Column(name = "activate_flag")
	private Integer activateFlag;
	@Column(name = "rating")
	private Integer rating;
	@Column(name = "comment")
	private String comment;

	/**
	 * @return the responseMpgId
	 */
	public Long getResponseMpgId() {
		return responseMpgId;
	}
	/**
	 * @param responseMpgId the responseMpgId to set
	 */
	public void setResponseMpgId(Long responseMpgId) {
		this.responseMpgId = responseMpgId;
	}
	/**
	 * @return the responseId
	 */
	public Long getResponseId() {
		return responseId;
	}
	/**
	 * @param responseId the responseId to set
	 */
	public void setResponseId(Long responseId) {
		this.responseId = responseId;
	}
	/**
	 * @return the paramId
	 */
	public Long getParamId() {
		return paramId;
	}
	/**
	 * @param paramId the paramId to set
	 */
	public void setParamId(Long paramId) {
		this.paramId = paramId;
	}
	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}
	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}
	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	/**
	 * @return the activateFlag
	 */
	public Integer getActivateFlag() {
		return activateFlag;
	}
	/**
	 * @param activateFlag the activateFlag to set
	 */
	public void setActivateFlag(Integer activateFlag) {
		this.activateFlag = activateFlag;
	}
	/**
	 * @return the rating
	 */
	public Integer getRating() {
		return rating;
	}
	/**
	 * @param rating the rating to set
	 */
	public void setRating(Integer rating) {
		this.rating = rating;
	}
	/**
	 * @return the comment
	 */
	public String getComment() {
		return comment;
	}
	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
	/**
	 * @return the paramRltId
	 */
	public Long getParamRltId() {
		return paramRltId;
	}
	/**
	 * @param paramRltId the paramRltId to set
	 */
	public void setParamRltId(Long paramRltId) {
		this.paramRltId = paramRltId;
	}

}
