/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.model;

import java.io.Serializable;
import java.util.List;

/**
 * @author Fujitsu
 *
 */
public class FeedbackEvaluation implements Serializable {
	
	private String paramName;
	/**
	 * @param paramName
	 * @param paramId
	 */
	public FeedbackEvaluation(String paramName, Long paramId) {
		super();
		
		System.out.println("hello---------");
		this.paramName = paramName;
		this.paramId = paramId;
	}
	public FeedbackEvaluation() {
		super();
		
		
	}


	private Long paramId;
	/**
	 * @return the paramId
	 */
	public Long getParamId() {
		return paramId;
	}
	/**
	 * @param paramId the paramId to set
	 */
	public void setParamId(Long paramId) {
		this.paramId = paramId;
	}

	private Double averageRating;
	private List<Reviewer> reviewer;
	private Reviewer review;
	/**
	 * @return the paramName
	 */
	/**
	 * @return the paramName
	 */
	public String getParamName() {
		return paramName;
	}
	/**
	 * @param paramName the paramName to set
	 */
	public void setParamName(String paramName) {
		this.paramName = paramName;
	}
	/**
	 * @return the paramId
	 */
	
	
	/**
	 * @return the averageRating
	 */
	public Double getAverageRating() {
		return averageRating;
	}
	/**
	 * @param averageRating the averageRating to set
	 */
	public void setAverageRating(Double averageRating) {
		this.averageRating = averageRating;
	}
	/**
	 * @return the reviewer
	 */
	public List<Reviewer> getReviewer() {
		return reviewer;
	}
	/**
	 * @param reviewer the reviewer to set
	 */
	public void setReviewer(List<Reviewer> reviewer) {
		this.reviewer = reviewer;
	}
	/**
	 * @param paramName
	 * @param paramId
	 * @param averageRating
	 * @param reviewer
	 */
	public FeedbackEvaluation(String paramName, Long paramId, Double averageRating, List<Reviewer> reviewer) {
		super();
		this.paramName = paramName;
		this.paramId = paramId;
		this.averageRating = averageRating;
		this.reviewer = reviewer;
	}
	public FeedbackEvaluation(String paramName, Long paramId, List<Reviewer> reviewer) {
		super();
		this.paramName = paramName;
		this.paramId = paramId;
	
		this.reviewer = reviewer;
	}
	/**
	 * @return the review
	 */
	public Reviewer getReview() {
		return review;
	}
	/**
	 * @param review the review to set
	 */
	public void setReview(Reviewer review) {
		this.review = review;
	}
	/**
	 * @param paramName
	 * @param paramId
	 * @param averageRating
	 * @param reviewer
	 * @param review
	 */
	public FeedbackEvaluation(String paramName, Long paramId, Double averageRating,
			Reviewer review) {
		super();
		this.paramName = paramName;
		this.paramId = paramId;
		this.averageRating = averageRating;
		
		this.review = review;
	}
	
	public FeedbackEvaluation(String paramName, Long paramId,
			Reviewer review) {
		super();
		this.paramName = paramName;
		this.paramId = paramId;
	
		
		this.review = review;
	}
	

}
