/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.model;

import java.io.Serializable;

/**
 * @author Fujitsu
 *
 */
public class Reviewer implements Serializable {
	  private Integer employeeId;
	  
	    private String employeeFname;
	    private String employeeMname;
	    private Integer rating;
	    private String comment;
		/**
		 * @return the employeeId
		 */
		public Integer getEmployeeId() {
			return employeeId;
		}
		/**
		 * @param employeeId the employeeId to set
		 */
		public void setEmployeeId(Integer employeeId) {
			this.employeeId = employeeId;
		}
		/**
		 * @return the employeeFname
		 */
		public String getEmployeeFname() {
			return employeeFname;
		}
		/**
		 * @param employeeFname the employeeFname to set
		 */
		public void setEmployeeFname(String employeeFname) {
			this.employeeFname = employeeFname;
		}
		/**
		 * @return the employeeMname
		 */
		public String getEmployeeMname() {
			return employeeMname;
		}
		/**
		 * @param employeeMname the employeeMname to set
		 */
		public void setEmployeeMname(String employeeMname) {
			this.employeeMname = employeeMname;
		}
		/**
		 * @return the rating
		 */
		public Integer getRating() {
			return rating;
		}
		/**
		 * @param rating the rating to set
		 */
		public void setRating(Integer rating) {
			this.rating = rating;
		}
		/**
		 * @return the comment
		 */
		public String getComment() {
			return comment;
		}
		/**
		 * @param comment the comment to set
		 */
		public void setComment(String comment) {
			this.comment = comment;
		}
		public Reviewer() {
			super();
			
		}
		/**
		 * @param employeeId
		 * @param employeeFname
		 * @param employeeMname
		 * @param rating
		 * @param comment
		 */
		public Reviewer(Integer employeeId, String employeeFname, String employeeMname, Integer rating
				) {
			super();
			this.employeeId = employeeId;
			this.employeeFname = employeeFname;
			this.employeeMname = employeeMname;
			this.rating = rating;
			//this.comment = comment;
		}

}
