/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author Fujitsu
 *
 */
public class TeamTask implements Serializable {

	private String teamName;
	private Integer teamId;
	private String employeeFName;
	private String employeeMName;
	private Integer employeeId;
	private Integer taskId;
	private String taskName;

	private String taskPriority;
	private Date taskDueDate;
	private String employeeTaskStatus;
	private Integer employeeTaskId;
	private String comment;
	private String reply;
	private Date completionDate;
	private Date taskStartDate;
	private List<TeamTask> teamTaskList;
	
	/**
	 * @return the teamName
	 */
	public String getTeamName() {
		return teamName;
	}
	/**
	 * @param teamName the teamName to set
	 */
	public void setTeamName(String teamName) {
		this.teamName = teamName;
	}
	/**
	 * @return the teamId
	 */
	public Integer getTeamId() {
		return teamId;
	}
	/**
	 * @param teamId the teamId to set
	 */
	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}
	/**
	 * @return the employeeFName
	 */
	public String getEmployeeFName() {
		return employeeFName;
	}
	/**
	 * @param employeeFName the employeeFName to set
	 */
	public void setEmployeeFName(String employeeFName) {
		this.employeeFName = employeeFName;
	}
	/**
	 * @return the employeeMName
	 */
	public String getEmployeeMName() {
		return employeeMName;
	}
	/**
	 * @param employeeMName the employeeMName to set
	 */
	public void setEmployeeMName(String employeeMName) {
		this.employeeMName = employeeMName;
	}
	/**
	 * @return the employeeId
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}
	/**
	 * @param employeeId the employeeId to set
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}
	/**
	 * @return the taskId
	 */
	public Integer getTaskId() {
		return taskId;
	}
	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}
	/**
	 * @return the taskName
	 */
	public String getTaskName() {
		return taskName;
	}
	/**
	 * @param taskName the taskName to set
	 */
	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}
	/**
	 * @return the taskPriority
	 */
	public String getTaskPriority() {
		return taskPriority;
	}
	/**
	 * @param taskPriority the taskPriority to set
	 */
	public void setTaskPriority(String taskPriority) {
		this.taskPriority = taskPriority;
	}
	/**
	 * @return the taskDueDate
	 */
	public Date getTaskDueDate() {
		return taskDueDate;
	}
	/**
	 * @param taskDueDate the taskDueDate to set
	 */
	public void setTaskDueDate(Date taskDueDate) {
		this.taskDueDate = taskDueDate;
	}
	/**
	 * @return the employeeTaskStatus
	 */
	public String getEmployeeTaskStatus() {
		return employeeTaskStatus;
	}
	/**
	 * @param employeeTaskStatus the employeeTaskStatus to set
	 */
	public void setEmployeeTaskStatus(String employeeTaskStatus) {
		this.employeeTaskStatus = employeeTaskStatus;
	}
	/**
	 * @return the employeeTaskId
	 */
	public Integer getEmployeeTaskId() {
		return employeeTaskId;
	}
	/**
	 * @param employeeTaskId the employeeTaskId to set
	 */
	public void setEmployeeTaskId(Integer employeeTaskId) {
		this.employeeTaskId = employeeTaskId;
	}
	/**
	 * @param teamName
	 * @param teamId
	 * @param employeeFName
	 * @param employeeMName
	 * @param employeeId
	 * @param taskId
	 * @param taskName
	 * @param taskPriority
	 * @param taskDueDate
	 * @param employeeTaskStatus
	 * @param employeeTaskId
	 */
	public TeamTask(String teamName, Integer teamId, String employeeFName, String employeeMName, Integer employeeId,
			Integer taskId, String taskName, String taskPriority, Date taskDueDate, String employeeTaskStatus,
			Integer employeeTaskId,String comment, String reply, Date completionDate, Date taskStartDate) {
		super();
		this.teamName = teamName;
		this.teamId = teamId;
		this.employeeFName = employeeFName;
		this.employeeMName = employeeMName;
		this.employeeId = employeeId;
		this.taskId = taskId;
		this.taskName = taskName;
		this.taskPriority = taskPriority;
		this.taskDueDate = taskDueDate;
		this.employeeTaskStatus = employeeTaskStatus;
		this.employeeTaskId = employeeTaskId;
		this.comment = comment;
		this.reply = reply;
		this.completionDate = completionDate;
		this.taskStartDate = taskStartDate;
	}
	public TeamTask() {}
	/**
	 * @return the createdDate
	 */

	/**
	 * @return the comment
	 */
	public String getComment() {
		return comment;
	}
	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
	/**
	 * @return the reply
	 */
	public String getReply() {
		return reply;
	}
	/**
	 * @param reply the reply to set
	 */
	public void setReply(String reply) {
		this.reply = reply;
	}
	/**
	 * @return the completionDate
	 */
	public Date getCompletionDate() {
		return completionDate;
	}
	/**
	 * @param completionDate the completionDate to set
	 */
	public void setCompletionDate(Date completionDate) {
		this.completionDate = completionDate;
	}
	/**
	 * @return the taskStartDate
	 */
	public Date getTaskStartDate() {
		return taskStartDate;
	}
	/**
	 * @param taskStartDate the taskStartDate to set
	 */
	public void setTaskStartDate(Date taskStartDate) {
		this.taskStartDate = taskStartDate;
	}
	/**
	 * @param comment
	 * @param reply
	 * @param completionDate
	 * @param taskStartDate
	 */
	/**
	 * @return the teamTaskList
	 */
	public List<TeamTask> getTeamTaskList() {
		return teamTaskList;
	}
	/**
	 * @param teamTaskList the teamTaskList to set
	 */
	public void setTeamTaskList(List<TeamTask> teamTaskList) {
		this.teamTaskList = teamTaskList;
	}


}
