/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.model;

import java.io.Serializable;

/**
 * @author Fujitsu
 *
 */
public class TeamGoals implements Serializable {

	public TeamGoals() {}
	

	

	private EmGoal goal;
	/**
	 * @param goal
	 * @param employee
	 * @param team
	 */
	public TeamGoals(EmGoal goal, EmEmployee employee, EmTeam team) {
		super();
		this.goal = goal;
		this.employee = employee;
		this.team = team;
	}
	public TeamGoals(EmGoal goal) {
		super();
		this.goal = goal;
		
	}



	private EmEmployee employee;
	private EmTeam team;
	/**
	 * @return the goal
	 */
	public EmGoal getGoal() {
		return goal;
	}
	/**
	 * @param goal the goal to set
	 */
	public void setGoal(EmGoal goal) {
		this.goal = goal;
	}
	/**
	 * @return the employee
	 */
	public EmEmployee getEmployee() {
		return employee;
	}
	/**
	 * @param employee the employee to set
	 */
	public void setEmployee(EmEmployee employee) {
		this.employee = employee;
	}
	/**
	 * @return the team
	 */
	public EmTeam getTeam() {
		return team;
	}
	/**
	 * @param team the team to set
	 */
	public void setTeam(EmTeam team) {
		this.team = team;
	}
}
