/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.service.impl;

import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.imageio.ImageIO;
import javax.servlet.http.HttpSession;

import org.hibernate.Hibernate;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.engine.jdbc.BlobProxy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.gomap.performance.master.constant.AppConstants;
import com.gomap.performance.organisastion.dao.EmployeeDao;
import com.gomap.performance.organisastion.dto.DesignationDto;
import com.gomap.performance.organisastion.dto.DesignationElementMapingDto;
import com.gomap.performance.organisastion.dto.EmEmployeeDto;
import com.gomap.performance.organisastion.dto.EmployeeDto;
import com.gomap.performance.organisastion.dto.EmployeeElementMpgDto;
import com.gomap.performance.organisastion.dto.EmployeeElementOperationDto;
import com.gomap.performance.organisastion.dto.ResponseDTO;
import com.gomap.performance.organisastion.dto.RoleElementOperationMpgDto;
import com.gomap.performance.organisastion.enumorg.ErrorCodeEnums;
import com.gomap.performance.organisastion.model.DesignationElementMaping;
import com.gomap.performance.organisastion.model.EmDepartment;
import com.gomap.performance.organisastion.model.EmDesignation;
import com.gomap.performance.organisastion.model.EmEmployee;
import com.gomap.performance.organisastion.model.EmployeeElementMpg;
import com.gomap.performance.organisastion.model.EmployeeElementOperationMpg;
import com.gomap.performance.organisastion.model.Person;
import com.gomap.performance.organisastion.model.RoleElementOperationMpg;
import com.gomap.performance.organisastion.service.AuditLogService;
import com.gomap.performance.organisastion.service.EmployeeService;


/**
 * @author krishnakant.bairagi
 *
 */
@Service
public class EmployeeServiceImpl implements EmployeeService {
	private static final Logger logger = LoggerFactory.getLogger(EmployeeServiceImpl.class);
	
	@Autowired
	private EmployeeDao empDao;
	@Autowired
	private HttpSession httpSession;
	
	 private static Session session;
	 
	 @Autowired
		private AuditLogService auditSrvc;
		
	 
	 @Autowired
	 private SessionFactory sessionFactory;
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.service.EmployeeService#addEmployee(com.gomap.performance.organisastion.dto.EmEmployeeDto)
	 */
	@Override
	@Transactional
	public ResponseDTO addEmployee(EmEmployeeDto employeeDto) throws Exception {
		ResponseDTO responseDTO=new ResponseDTO();
		try {
			logger.debug("addEmployee ");
			EmEmployee emEmployee=new EmEmployee();
			String pwd="Password@2020";
			emEmployee.setEmployeePassword(pwd);
			
			
			if(employeeDto.getDepartmentId()!=null)
			{
				emEmployee.setDepartmentId(employeeDto.getDepartmentId());
			}
			if(employeeDto.getDesignationId()!=null)
			{
				emEmployee.setDesignationId(employeeDto.getDepartmentId());
			}
//			if(employeeDto.getGender()!=null)
//			{
//				emEmployee.setGender(employeeDto.getGender());
//			}
			if(employeeDto.getEmployeeEmail()!=null)
			{
				emEmployee.setEmployeeEmail(employeeDto.getEmployeeEmail());
			}
			if(employeeDto.getEmployeeFname()!=null)
			{
				emEmployee.setEmployeeFname(employeeDto.getEmployeeFname());
			}
			if(employeeDto.getEmployeeMname()!=null)
			{
				emEmployee.setEmployeeMname(employeeDto.getEmployeeMname());
			}
			if(employeeDto.getEmployeeMobileNo()!=null)
			{
				emEmployee.setEmployeeMobileNo(employeeDto.getEmployeeMobileNo());
			}else {
				emEmployee.setEmployeeMobileNo("1111111111");
			}
			
			emEmployee.setFileId(-1);
			
				
			
			if(employeeDto.getEmployeeProfileImg()!=null)
			{
				emEmployee.setEmployeeProfileImg(employeeDto.getEmployeeProfileImg());
			}
			if(employeeDto.getEmployeeCode()!=null)
			{
				emEmployee.setEmployeeCode(employeeDto.getEmployeeCode());
			}
			emEmployee.setActivateFlag(AppConstants.ACTIVE_FLAG);
			emEmployee.setEmployeeCreatedDate(new Date());
			
			empDao.storeEmployeeData(emEmployee);
			
			if(employeeDto.getEmployeeElementMappingList()!=null)
			{
				EmployeeElementMpg employeeElementMpg=null;
				for(EmployeeElementMpgDto employeeElementMpgDto:employeeDto.getEmployeeElementMappingList())
				{
					employeeElementMpg=new EmployeeElementMpg();
					employeeElementMpg.setElementId(employeeElementMpgDto.getElementId());
					employeeElementMpg.setEmployeeId(emEmployee.getEmployeeId());
					
					
					employeeElementMpg.setActivateFlag(AppConstants.ACTIVE_FLAG);
					employeeElementMpg.setCreatedDate(new Date());
					empDao.mapEmployeeElement(employeeElementMpg);
					
					if(employeeElementMpgDto.getEmployeeElementOprationList()!=null)
					{
						//for(OperationMaster)
						for(EmployeeElementOperationDto employeeElementOperationDto:employeeElementMpgDto.getEmployeeElementOprationList())
						{
							EmployeeElementOperationMpg employeeElementOperationMpg=new EmployeeElementOperationMpg();
							employeeElementOperationMpg.setOperationId(employeeElementOperationDto.getOperationId());
							employeeElementOperationMpg.setActivateFlag(AppConstants.ACTIVE_FLAG);
							employeeElementOperationMpg.setEmployeeElementMpgId(employeeElementMpg.getEmployeeElementMpgId());
							employeeElementOperationMpg.setCreatedDate(new Date());
							//departmentAndDesignationDao.mapOperation(roleElementOperationMpg);
							empDao.mapOperation(employeeElementOperationMpg);
							
						}
						
					}
				}
			}
			
			auditSrvc.saveAuditLog("Employee  Created", "Employee ", "1", new Date());
			
			responseDTO.setSuccessMsg("Employee created Successfully");
			responseDTO.setDataObj(emEmployee);
			responseDTO.setErrorCode(ErrorCodeEnums.NO_ERROR.getErrorCode());
		} catch (Exception e) {
			// TODO: handle exception
			responseDTO.setErrorCode(411);
			responseDTO.setErrorMsg(e.getMessage());
			logger.error("Getting Error while creating Employee");
		}
		// TODO Auto-generated method stub
		return responseDTO;
	}
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.service.EmployeeService#employeeRoleMapping(com.gomap.performance.organisastion.dto.EmEmployeeDto)
	 */
	@Override
	public ResponseDTO employeeRoleMapping(EmEmployeeDto employeeDto) throws Exception {
		// TODO Auto-generated method stub
		return null;
	}
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.service.EmployeeService#employeeDepratmentMapping(com.gomap.performance.organisastion.dto.EmEmployeeDto)
	 */
	@Override
	public ResponseDTO employeeDepratmentMapping(EmEmployeeDto employeeDto) throws Exception {
		// TODO Auto-generated method stub
		return null;
	}
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.service.EmployeeService#getMySkill()
	 */
	@Override
	public ResponseDTO getMySkill() throws Exception {
		// TODO Auto-generated method stub
		return null;
	}
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.service.EmployeeService#getMyTask()
	 */
	@Override
	public ResponseDTO getMyTask() throws Exception {
		// TODO Auto-generated method stub
		return null;
	}
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.service.EmployeeService#getMyGoal()
	 */
	@Override
	public ResponseDTO getMyGoal() throws Exception {
		// TODO Auto-generated method stub
		return null;
	}
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.service.EmployeeService#getEmployeeList(java.lang.Integer)
	 */
	@Override
	@Transactional
	public ResponseDTO getEmployeeList(Integer employeeId,String emailId) throws Exception {

		ResponseDTO responseDTO=new ResponseDTO();
		try {
			logger.debug("getting getEmployeeList employeeId="+employeeId);
			List<EmEmployee> employeeList=empDao.getEmployeeList(employeeId,emailId);
			responseDTO.setDataObj(employeeList);
			responseDTO.setErrorCode(ErrorCodeEnums.NO_ERROR.getErrorCode());
		} catch (Exception e) {
			// TODO: handle exception
			responseDTO.setErrorCode(411);
			responseDTO.setErrorMsg(e.getMessage());
			logger.error(" Error while getting EmployeeList");
		}
		// TODO Auto-generated method stub
		return responseDTO;
	
	}
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.service.EmployeeService#updateEmployee(com.gomap.performance.organisastion.dto.EmEmployeeDto)
	 */
	@Override
	@Transactional
	public ResponseDTO updateEmployee(EmEmployeeDto employeeDto) throws Exception {
		ResponseDTO responseDTO=new ResponseDTO();
		try {
			logger.debug("updateEmployee ");
			if(employeeDto!=null && employeeDto.getEmployeeId()!=null)
			{
				List<EmEmployee> employeeList=empDao.getEmployeeList(employeeDto.getEmployeeId(),null);
				if(employeeList==null ||  employeeList.isEmpty())
				{
					responseDTO.setDataObj(null);
					responseDTO.setErrorMsg("Employee data is not available in system");
					responseDTO.setErrorCode(411);
					return 	responseDTO;				
				}else {
					EmEmployee emEmployee=employeeList.get(0);
							
							if(employeeDto.getDepartmentId()!=null)
							{
								emEmployee.setDepartmentId(employeeDto.getDepartmentId());
							}
							
							if(employeeDto.getDesignationId()!=null)
							{
								emEmployee.setDesignationId(employeeDto.getDepartmentId());
							}
							
//							if(employeeDto.getGender()!=null)
//							{
//								emEmployee.setGender(employeeDto.getGender());
//							}
							if(employeeDto.getEmployeeEmail()!=null)
							{
								emEmployee.setEmployeeEmail(employeeDto.getEmployeeEmail());
							}
							if(employeeDto.getEmployeeFname()!=null)
							{
								emEmployee.setEmployeeFname(employeeDto.getEmployeeFname());
							}
							if(employeeDto.getEmployeeMname()!=null)
							{
								emEmployee.setEmployeeMname(employeeDto.getEmployeeMname());
							}
							if(employeeDto.getEmployeeMobileNo()!=null)
							{
								emEmployee.setEmployeeMobileNo(employeeDto.getEmployeeMobileNo());
							}else {
								emEmployee.setEmployeeMobileNo("1111111111");
							}
							if(employeeDto.getEmployeePassword()!=null)
							{
								emEmployee.setEmployeePassword(employeeDto.getEmployeePassword());
							}
							if(employeeDto.getEmployeeProfileImg()!=null)
							{
								emEmployee.setEmployeeProfileImg(employeeDto.getEmployeeProfileImg());
							}
							if(employeeDto.getEmployeeCode()!=null)
							{
								emEmployee.setEmployeeCode(employeeDto.getEmployeeCode());
							}
							if(employeeDto.getActivateFlag()!=null)
							{
								emEmployee.setActivateFlag(employeeDto.getActivateFlag());
							}else {
								emEmployee.setActivateFlag(AppConstants.ACTIVE_FLAG);
							}
							
							emEmployee.setEmployeeUpdatedDate(new Date());
							empDao.updateEmployee(emEmployee);
							// permisson start

							EmployeeElementMpg employeeElementMpg=null;
							
							for(EmployeeElementMpgDto employeeElementMpgDto:employeeDto.getEmployeeElementMappingList())
							{
								if(employeeElementMpgDto.getEmployeeElementMpgId()==null)
								{
									// insert new element
									// then store data for operation

									employeeElementMpg=new EmployeeElementMpg();
										
									employeeElementMpg.setEmployeeId(emEmployee.getEmployeeId());
									
									employeeElementMpg.setElementId(employeeElementMpgDto.getElementId());
									employeeElementMpg.setActivateFlag(AppConstants.ACTIVE_FLAG);
									employeeElementMpg.setCreatedDate(new Date());
										empDao.mapEmployeeElement(employeeElementMpg);
										
										if(employeeElementMpgDto.getEmployeeElementOprationList()!=null)
										{
											//for(OperationMaster)
											for(EmployeeElementOperationDto employeeElementOperationDto:employeeElementMpgDto.getEmployeeElementOprationList())
											{
												EmployeeElementOperationMpg employeeElementOperationMpg=new EmployeeElementOperationMpg();
												employeeElementOperationMpg.setOperationId(employeeElementOperationDto.getOperationId());
												employeeElementOperationMpg.setActivateFlag(AppConstants.ACTIVE_FLAG);
												employeeElementOperationMpg.setEmployeeElementMpgId(employeeElementMpg.getEmployeeElementMpgId());
												employeeElementOperationMpg.setCreatedDate(new Date());
												empDao.mapOperation(employeeElementOperationMpg);
												
											}
											
										}
									
								
								}else {
									if(employeeElementMpgDto.getEmployeeElementOprationList()!=null)
									{
										for(EmployeeElementOperationDto emploElementOperationDto:employeeElementMpgDto.getEmployeeElementOprationList())
										{
											if(emploElementOperationDto.getEmployeeElementOperationId()==null)
											{
												EmployeeElementOperationMpg employeeElementOperationMpg=new EmployeeElementOperationMpg();
												employeeElementOperationMpg.setOperationId(emploElementOperationDto.getOperationId());
												employeeElementOperationMpg.setActivateFlag(AppConstants.ACTIVE_FLAG);
												employeeElementOperationMpg.setEmployeeElementMpgId(employeeElementMpgDto.getEmployeeElementMpgId());
												employeeElementOperationMpg.setCreatedDate(new Date());
												empDao.mapOperation(employeeElementOperationMpg);
												
												// insert new  operation
											}else
											{
												if(emploElementOperationDto.getEmployeeElementOperationId()!=null && emploElementOperationDto.getActivateFlag()!=null && emploElementOperationDto.getActivateFlag().equals(AppConstants.IN_ACTIVE_FLAG))
												{
													//inactive operation here
													EmployeeElementOperationMpg employeeElementOperationMpg=new EmployeeElementOperationMpg();
													employeeElementOperationMpg.setEmployeeElementOperationId(emploElementOperationDto.getEmployeeElementOperationId());
													employeeElementOperationMpg.setOperationId(emploElementOperationDto.getOperationId());
													employeeElementOperationMpg.setActivateFlag(AppConstants.IN_ACTIVE_FLAG);
													employeeElementOperationMpg.setEmployeeElementMpgId(employeeElementMpgDto.getEmployeeElementMpgId());
													employeeElementOperationMpg.setUpdatedDate(new Date());
													empDao.updateOperation(employeeElementOperationMpg);
													
												}
											}
										}
									}
								}
							}
						
							
							// permisson end
							
							responseDTO.setDataObj(emEmployee);
							responseDTO.setErrorCode(ErrorCodeEnums.NO_ERROR.getErrorCode());
							responseDTO.setSuccessMsg("Employee data updated successfully!!");
							
				}
			}
			else {
				responseDTO.setDataObj(null);
				responseDTO.setErrorMsg("Employee id can not be null");
				responseDTO.setErrorCode(411);
			}
			
		} catch (Exception e) {
			// TODO: handle exception
			responseDTO.setErrorCode(411);
			responseDTO.setErrorMsg(e.getMessage());
			logger.error("Getting Error while updating Employee",e);
		}
		// TODO Auto-generated method stub
		return responseDTO;
	}
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.service.EmployeeService#getAllEmployee()
	 */
	@Override
	@Transactional
	public ResponseDTO getAllEmployee() throws Exception {
		// TODO Auto-generated method stub
		logger.info("getAllEmployee ");
		ResponseDTO responseDTO=null;
		try {
			responseDTO=new ResponseDTO();
			responseDTO.setDataObj(empDao.getAllEmplyeeData());
			responseDTO.setSuccessMsg("Employee sent successfully");
			responseDTO.setErrorCode(ErrorCodeEnums.NO_ERROR.getErrorCode());
			;
			
		} catch (Exception e) {
			// TODO: handle exception
			logger.error("Error in getAllEmployee",e);
			responseDTO.setDataObj(e);
			responseDTO.setErrorMsg(e.getMessage());
			responseDTO.setErrorCode(411);
		}
		return responseDTO;
	}
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.service.EmployeeService#getEmployeeWithElements(java.lang.Integer)
	 */
	@Override
	@Transactional
	public ResponseDTO getEmployeeWithElements(Integer employeeId) throws Exception {
		// TODO Auto-generated method stub
		logger.info("getting getEmployeeWithElements employeeId="+employeeId);
		ResponseDTO responseDTO=new ResponseDTO();
		try {
			
			List<EmployeeElementMpg> employeeElementMpg=empDao.getEmployeeElement(employeeId);
			EmployeeElementMpgDto employeeElementMpgDto=new EmployeeElementMpgDto();
			//List<EmployeeElementOperationDto> employeeElementOperationDtos=new ArrayList<EmployeeElementOperationDto>();
			List<EmployeeElementMpgDto> employeeElementMpgDtos=new ArrayList<EmployeeElementMpgDto>();
			//EmployeeElementMpgDto employeeElementMpgDto2=new EmployeeElementMpgDto();
			EmployeeElementOperationDto elementOperationMpgDto=new EmployeeElementOperationDto();
			EmEmployeeDto employeeDto=new EmEmployeeDto();
			List<EmEmployee> employeeList=empDao.getEmployeeList(employeeId,null);
			employeeDto.setEmployeeId(employeeId);
			employeeDto.setEmployeeEmail(employeeList.get(0).getEmployeeEmail());
			//hhdesignationDto.setDepartmentId(desigList.get(0).getDepartmentId());
			List<EmployeeElementOperationDto> operationMasterDtos=null;
			for(EmployeeElementMpg employeeElementMpg2:employeeElementMpg)
			{
				operationMasterDtos = new ArrayList<EmployeeElementOperationDto>();
				employeeElementMpgDto=new EmployeeElementMpgDto();
				List<EmployeeElementOperationMpg> masterDtos = empDao.getEmployeeElementOperation(employeeElementMpg2.getEmployeeElementMpgId());
						
				if (masterDtos != null && !masterDtos.isEmpty()) {
					for (EmployeeElementOperationMpg elementOperationMpg : masterDtos) {

						elementOperationMpgDto = new EmployeeElementOperationDto();
						elementOperationMpgDto
								.setEmployeeElementMpgId(elementOperationMpg.getEmployeeElementMpgId());
						elementOperationMpgDto.setOperationId(elementOperationMpg.getOperationId());
						elementOperationMpgDto
								.setEmployeeElementOperationId(elementOperationMpg.getEmployeeElementOperationId());
						operationMasterDtos.add(elementOperationMpgDto);
					}
					employeeElementMpgDto.setEmployeeElementOprationList(operationMasterDtos);
					employeeElementMpgDto.setEmployeeId(employeeElementMpg2.getEmployeeId());
					employeeElementMpgDto.setElementId(employeeElementMpg2.getElementId());
					employeeElementMpgDto.setEmployeeElementMpgId(employeeElementMpg2.getEmployeeElementMpgId());
							
					employeeElementMpgDtos.add(employeeElementMpgDto);
				}
			}
			employeeDto.setEmployeeElementMappingList(employeeElementMpgDtos);
			responseDTO.setDataObj(employeeDto);
			responseDTO.setSuccessMsg("Data sent");
			responseDTO.setErrorCode(ErrorCodeEnums.NO_ERROR.getErrorCode());
			
		} catch (Exception e) {
			// TODO: handle exception
			responseDTO.setDataObj(e);
			responseDTO.setErrorMsg(e.getMessage());
			responseDTO.setErrorCode(411);
		}
		return responseDTO;
	}
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.service.EmployeeService#deleteEmployee(com.gomap.performance.organisastion.dto.EmEmployeeDto)
	 */
	@Override
	@Transactional
	public ResponseDTO deleteEmployee(EmEmployeeDto employeeDto) throws Exception {
		logger.debug("start  deleteEmployee for empId=" + employeeDto.getEmployeeId());
		ResponseDTO responseDTO = new ResponseDTO();
		try {
			EmEmployee emEmployee = new EmEmployee();
			if (employeeDto == null && employeeDto.getEmployeeId() == null) {
				responseDTO.setErrorCode(411);
				responseDTO.setErrorMsg("Employee parameter can not be null");
			} else {
			
				List<EmEmployee> emplList = empDao.getEmployeeList(employeeDto.getEmployeeId(),null);
						
				if (emplList.isEmpty()) {
					responseDTO.setErrorCode(412);
					responseDTO.setErrorMsg("Employee data is not availabe in system");
				} else {
					 emEmployee = emplList.get(0);
				
					 emEmployee.setActivateFlag(AppConstants.IN_ACTIVE_FLAG);
					 emEmployee.setEmployeeUpdatedDate(new Date());
					 empDao.updateEmployee(emEmployee);
						responseDTO.setDataObj(employeeDto);
						responseDTO.setSuccessMsg("Data deleted..");
						responseDTO.setErrorCode(ErrorCodeEnums.NO_ERROR.getErrorCode());
					

				}

			}

			
		} catch (Exception e) {
			// TODO: handle exception
			responseDTO.setErrorCode(411);
			responseDTO.setErrorMsg(e.getMessage());
			logger.error(" Error while deleting deleteTeam");
		}
		// TODO Auto-generated method stub
		return responseDTO;

	}
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.service.EmployeeService#storeFiles()
	 */
	@Override
	@Transactional
	public ResponseDTO storeFiles(Person pp,byte[] bb) throws Exception {
		// TODO Auto-generated method stub
		ResponseDTO responseDTO = new ResponseDTO();
		try {
			//String filePath="C:\\Users\\Fujitsu\\Downloads\\Emformance_HTML_New\\assets\\img\\face-3.jpg";
			
			 //File file = new File(filePath);
			//FileInputStream inputStream = new FileInputStream(file);
	        Blob blob = Hibernate.getLobCreator(sessionFactory.getCurrentSession())
	                            .createBlob(bb);
	        Blob blob1=BlobProxy.generateProxy(bb);
	       
	        
	       
	      
			pp.setPhoto(blob1);
			empDao.storePerson(pp);
			responseDTO.setDataObj(pp);
			responseDTO.setSuccessMsg("good");
			
		} catch (Exception e) {
			// TODO: handle exceptionreturn null;
			logger.error("error",e);
			e.printStackTrace();
	}
	return responseDTO;
		}
	
	@Override
	@Transactional
	public ResponseDTO getFiles(Person pp) throws Exception {
		// TODO Auto-generated method stubPerson pp
		ResponseDTO responseDTO = new ResponseDTO();
		try {
			List<Person> personList=empDao.getPerson(pp.getId());
			
			if(personList!=null && !personList.isEmpty())
			{
				
				responseDTO.setDataObj(personList.get(0));
			}
		
			
			
			InputStream is = personList.get(0).getPhoto().getBinaryStream();
			//String str = convert(is);
			
			File file = new File("C:\\Files\\kk"+System.currentTimeMillis()+"."+personList.get(0).getFileType());
			FileOutputStream outputStream = new FileOutputStream(file);
			 byte[] buffer = new byte[1024];

             // Get the binary stream of our BLOB data
            // InputStream is = rs.getBinaryStream("image");
             while (is.read(buffer) > 0) {
            	 outputStream.write(buffer);
             }
			//BufferedImage bf=ImageIO.read(is);
			//ImageIO.write(bf, "jpg", outputStream);
			//outputStream.write(str.getBytes());
             
			outputStream.close();
			responseDTO.setDataObj(file.getAbsolutePath());
			
			responseDTO.setSuccessMsg("good");
			
		} catch (Exception e) {
			// TODO: handle exceptionreturn null;
			logger.error("error",e);
			e.printStackTrace();
	}
	return responseDTO;
		}
	 private static byte[] readBytesFromFile(String filePath) throws IOException {
	        File inputFile = new File(filePath);
	        FileInputStream inputStream = new FileInputStream(inputFile);
	         
	        byte[] fileBytes = new byte[(int) inputFile.length()];
	        inputStream.read(fileBytes);
	        inputStream.close();
	         
	        return fileBytes;
	    }
	 private static String convert(InputStream is) {
			BufferedInputStream bis = new BufferedInputStream(is);
			ByteArrayOutputStream buf = new ByteArrayOutputStream();
			int result;
			String str = null;
			try {
				result = bis.read();

				while (result != -1) {
					buf.write((byte) result);
					result = bis.read();
				}
				str = buf.toString("UTF-8");
			} catch (IOException e) {
				e.printStackTrace();
			}
			return str;
		}
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.service.EmployeeService#mapEmployeeFile(java.lang.Integer, java.lang.Integer)
	 */
	@Override
	@Transactional
	public EmEmployee mapEmployeeFile(Integer fileId, Integer employeeId) throws Exception {
		// TODO Auto-generated method stub
		EmEmployee emEmployee=new EmEmployee();
		try {
			List<EmEmployee> employeeList=empDao.getEmployeeList(employeeId,null);
			if(employeeList!=null && !employeeList.isEmpty())
			{
				  emEmployee = employeeList.get(0);
				 
				 emEmployee.setFileId(fileId);
				 empDao.updateEmployee(emEmployee);
			}
			
		} catch (Exception e) {
			// TODO: handle exception
			logger.error("Error while update file id for employee");
		}
		return emEmployee;
	}
}
