/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.master.dao;

import java.util.List;

import com.gomap.performance.master.model.CompanyMaster;
import com.gomap.performance.master.model.IndustryMaster;

/**
 * @author krishnakant.bairagi
 *
 */
public interface CompanyDao {
	public List<CompanyMaster> getCompanyDetails(CompanyMaster companyMaster) throws Exception;
	public CompanyMaster storeCompanyData(CompanyMaster companyMaster) throws Exception;
	
	public CompanyMaster updateCompany(CompanyMaster companyMaster) throws Exception;
	public List<CompanyMaster> getCompanyByPortalName(String portalName) throws Exception;
	public List<IndustryMaster> getIndustryMaster(Integer industryId) throws Exception;

}
