/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.master.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;

/**
 * @author Fujitsu
 *
 */
@Configuration
@EnableWebMvc
public class CorsConfig extends WebMvcConfigurerAdapter {

	/* (non-Javadoc)
	 * @see org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter#addCorsMappings(org.springframework.web.servlet.config.annotation.CorsRegistry)
	 */
	@Override
	public void addCorsMappings(CorsRegistry registry) {
		// TODO Auto-generated method stub
		System.out.println("here------------");
		registry.addMapping("/**").allowedHeaders("header1", "header2", "header3")
		.exposedHeaders("header1", "header2")
        .allowedMethods("GET", "POST").allowedOrigins("*");
		super.addCorsMappings(registry);
	}

}
