/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.master.service;

import com.gomap.performance.master.dto.CompanyMasterDto;
import com.gomap.performance.master.dto.EmployeeDto;
import com.gomap.performance.master.dto.ResponseDTO;
import com.gomap.performance.master.model.CompanyMaster;

/**
 * @author krishnakant.bairagi
 *
 */
public interface CompanyService {
	public ResponseDTO addCompany(CompanyMasterDto companyMasterDto);
	public ResponseDTO deleteCompany(CompanyMasterDto companyMasterDto);
	public ResponseDTO updateCompany(CompanyMasterDto companyMasterDto);
	public ResponseDTO getCompanyDetails(CompanyMasterDto companyMasterDto);
	public ResponseDTO searchForPortalName(String companyName);
	public boolean generateApiByPortalName(String portalName);
	public ResponseDTO getIndustry(Integer industryId);
	//public ResponseDTO getUserPortalName(String emailId);
	
}
