/**

 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.master.service;

/**
 * @author Fujitsu
 *
 */
public interface EmailService {
	public void sendEmail(String tokenId,String toEmail,String password);
	

}
