/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.controller;

import org.springframework.web.bind.annotation.RestController;

/**
 * @author krishnakant.bairagi
 *
 */
@RestController
public class CommonController {

}
