/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.master.dao.impl;

import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Restrictions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.gomap.performance.master.constant.AppConstants;
import com.gomap.performance.master.dao.AdminEmployeeDao;
import com.gomap.performance.master.model.EmployeeMaster;

/**
 * @author krishnakant.bairagi
 *
 */
@Repository
public class AdminEmployeeDaoImpl implements AdminEmployeeDao {
	
	@Autowired
	private SessionFactory sessionFactory;


	/* (non-Javadoc)
	 * @see com.gomap.performance.master.dao.EmployeeDao#getUserByUserId(java.lang.String)
	 */
	@Override
	public EmployeeMaster getUserByUserId(String userId) throws Exception {
		// TODO Auto-generated method stub

		Criteria criteria = this.sessionFactory.getCurrentSession()
				.createCriteria(EmployeeMaster.class);
		criteria.add(Restrictions.eq("upUserId", userId).ignoreCase());
		criteria.add(Restrictions.eq("upUserStatus", AppConstants.ACTIVE_FLAG));
		return (EmployeeMaster) criteria.uniqueResult();
	
		
	}


	/* (non-Javadoc)
	 * @see com.gomap.performance.master.dao.EmployeeDao#storeEmployeeData(com.gomap.performance.master.model.EmployeeMaster)
	 */
	@Override
	public EmployeeMaster storeEmployeeData(EmployeeMaster employeeMaster) throws Exception {
		// TODO Auto-generated method stub
		Session ss=sessionFactory.getCurrentSession();
		 ss.save(employeeMaster);
		return employeeMaster;
	}

}
