/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.service;

import java.util.Date;

import com.gomap.performance.organisastion.dto.ResponseDTO;

/**
 * @author Fujitsu
 *
 */
public interface AuditLogService {
	public ResponseDTO saveAuditLog(String action, String action_Type, String createdBy, Date createdDate) throws Exception;
	public ResponseDTO getAuditLog(String action, String action_Type, String createdBy, Date createdDate) throws Exception;


}
