/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.service;

import org.springframework.web.multipart.MultipartFile;

import com.gomap.performance.organisastion.dto.DepartmentDto;
import com.gomap.performance.organisastion.dto.ElementMasterDto;
import com.gomap.performance.organisastion.dto.EmParamsConfigDto;
import com.gomap.performance.organisastion.dto.OperationMasterDto;
import com.gomap.performance.organisastion.dto.ResponseDTO;

/**
 * @author Fujitsu
 *
 */
public interface CommonService {
	public ResponseDTO getElements() throws Exception;
	public ResponseDTO getOperation() throws Exception;
	public ResponseDTO createElement(ElementMasterDto elementMasterDto) throws Exception;
	public ResponseDTO createParameter(EmParamsConfigDto emParamsConfigDto) throws Exception;
	
	/**
	 * @param type
	 * @return
	 * @throws Exception
	 */
	public ResponseDTO getParameter(Integer type) throws Exception;
	public ResponseDTO createOperation(OperationMasterDto operationMasterDto) throws Exception;
	/**
	 * @param employeeId
	 * @return
	 * @throws Exception
	 */
	public ResponseDTO getDashBoardData(Integer employeeId) throws Exception;
	public ResponseDTO  storeFiles(String module,MultipartFile file,Integer id) throws Exception;
	public ResponseDTO  getEmployeeFiles(Integer fileId) throws Exception;

	


}
