/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.service;


import com.gomap.performance.organisastion.dto.DepartmentDto;
import com.gomap.performance.organisastion.dto.DesignationDto;
import com.gomap.performance.organisastion.dto.ResponseDTO;

/**
 * @author krishnakant.bairagi
 *
 */
public interface DepartmentAndDesignationService {
	
	public ResponseDTO createDepartment(DepartmentDto departmentDto) throws Exception;
	public ResponseDTO createDesignation(DesignationDto  designationDto) throws Exception;
	
	
	public ResponseDTO updateDepartment(DepartmentDto departmentDto) throws Exception;
	public ResponseDTO updateDesignation(DesignationDto  designationDto) throws Exception;
	
	
	public ResponseDTO deleteDepartment(DepartmentDto departmentDto) throws Exception;
	public ResponseDTO deleteDesignation(DesignationDto  designationDto) throws Exception;
	
	public ResponseDTO getDepartment(Integer departmentId) throws Exception;
	public ResponseDTO getDesignation(Integer designationId,Integer departmentId) throws Exception;
	
	
	
	
}
