/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.service;

import java.util.List;

import com.gomap.performance.organisastion.dto.EmEmployeeDto;
import com.gomap.performance.organisastion.dto.EmployeePerformanceMasterDto;
import com.gomap.performance.organisastion.dto.EvalutionPeriodMasterDto;
import com.gomap.performance.organisastion.dto.ResponseDTO;

/**
 * @author Fujitsu
 *
 */
public interface EvalutionService {
	
	public ResponseDTO createEvaluationPeriod(EvalutionPeriodMasterDto evalutionPeriodMasterDto) throws Exception;
	public ResponseDTO getCurrentEvaluationPeriod() throws Exception;
	public ResponseDTO getAllEvaluationPeriod() throws Exception;
	public ResponseDTO  updateEvaluationPeriod(EvalutionPeriodMasterDto evalutionPeriodMasterDto) throws Exception;

	
	public ResponseDTO storeRating(List<EmployeePerformanceMasterDto> employeePerformanceMasterDto) throws Exception;
	public ResponseDTO getEmployeeRating(EmployeePerformanceMasterDto employeePerformanceMasterDto) throws Exception;
	public ResponseDTO updateRating(List<EmployeePerformanceMasterDto> employeePerformanceMasterDto) throws Exception;
	
	public ResponseDTO checkEvalution(Integer employeeId,Integer evaluterId) throws Exception;


}
