/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.service;


import java.util.List;

import com.gomap.performance.organisastion.dto.EmEmployeeSkillMpgDto;
import com.gomap.performance.organisastion.dto.EmSkillDto;
import com.gomap.performance.organisastion.dto.ResponseDTO;

/**
 * @author krishnakant.bairagi
 *
 */
public interface SkillService {
	public ResponseDTO createSkill(EmSkillDto emSkillDto) throws Exception;
	public ResponseDTO updateSkill(EmSkillDto emSkillDto) throws Exception;
	public ResponseDTO deleteSkill(EmSkillDto emSkillDto) throws Exception;
	public ResponseDTO getSkill(EmSkillDto emSkillDto) throws Exception;
	public ResponseDTO mapEmployeeSkill(EmEmployeeSkillMpgDto emEmployeeSkillMpgDto) throws Exception;
	
	public ResponseDTO updateEmployeeSkill(EmEmployeeSkillMpgDto emEmployeeSkillMpgDto) throws Exception;
	public ResponseDTO deleteEmployeeSkill(EmEmployeeSkillMpgDto emEmployeeSkillMpgDto) throws Exception;
	public ResponseDTO getEmployeeSkill(EmEmployeeSkillMpgDto emEmployeeSkillMpgDto) throws Exception;
	public ResponseDTO processSkilList(List<EmEmployeeSkillMpgDto> emEmployeeSkillMpgDtoList) throws Exception;
	
}
