/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.service;


import java.util.List;

import com.gomap.performance.organisastion.dto.EmTaskDto;
import com.gomap.performance.organisastion.dto.EmployeeTaskMpgDto;
import com.gomap.performance.organisastion.dto.ResponseDTO;
import com.gomap.performance.organisastion.model.EmployeeTaskMpg;

/**
 * @author krishnakant.bairagi
 *
 */
public interface TaskService {
	public ResponseDTO createTask(EmTaskDto emTaskDto) throws Exception;
	public ResponseDTO updateTask(EmTaskDto emTaskDto) throws Exception;
	public ResponseDTO getTask(EmTaskDto emTaskDto) throws Exception;
	public ResponseDTO deleteTask(EmTaskDto emTaskDto) throws Exception;
	public ResponseDTO getMyTeamTask(Integer createdBy,Integer assignToId,Integer asssignById,Integer projectId,Integer teamId) throws Exception;
	
	/**
	 * @param employeeTaskMpgDtoList
	 * @return
	 * @throws Exception
	 */
	public ResponseDTO mapEmployeeTask(List<EmployeeTaskMpgDto> employeeTaskMpgDtoList) throws Exception;
	/**
	 * @param taskId
	 * @param employeeId
	 * @return
	 * @throws Exception
	 */
	ResponseDTO getEmployeeTaskList(Integer taskId, Integer employeeId) throws Exception;
	
}
