/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.service;


import com.gomap.performance.organisastion.dto.EmTeamDto;
import com.gomap.performance.organisastion.dto.EmTeamMemberDto;
import com.gomap.performance.organisastion.dto.ResponseDTO;
import com.gomap.performance.organisastion.model.EmTeam;

/**
 * @author krishnakant.bairagi
 *
 */
public interface TeamManagmentService {
	public ResponseDTO createTeam(EmTeamDto emTeamDto) throws Exception;
	public ResponseDTO updateTeam(EmTeamDto emTeamDto) throws Exception;
	public ResponseDTO getTeam(EmTeamDto emTeamDto) throws Exception;
	public ResponseDTO addTeamMember(EmTeamMemberDto emTeamMemberDto) throws Exception;
	public ResponseDTO removeTeamMember(EmTeamMemberDto emTeamMemberDto) throws Exception;
	public ResponseDTO getTeamMember(EmTeamMemberDto emTeamMemberDto) throws Exception;
	
}
