/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dao;

import java.util.List;

import com.gomap.performance.organisastion.model.DashBoardInfo;
import com.gomap.performance.organisastion.model.ElementMaster;
import com.gomap.performance.organisastion.model.EmParamsConfig;
import com.gomap.performance.organisastion.model.FileMaster;
import com.gomap.performance.organisastion.model.OperationMaster;

/**
 * @author Fujitsu
 *
 */
public interface CommonDao {
	
	public List<ElementMaster> getElements();
	public List<OperationMaster> getOperations();
	public ElementMaster createElement(ElementMaster elementMaster);
	public EmParamsConfig createParams(EmParamsConfig emParamsConfig);
	public List<EmParamsConfig> getParameter(Integer type);
	public OperationMaster createOperation(OperationMaster operationMaster);
	public DashBoardInfo getDashBoardInfo(Integer employeeId);
	public FileMaster storeFile(FileMaster fileMaster);
	public FileMaster updateFile(FileMaster fileMaster);
	public FileMaster getFile(Integer fileId);

}
