/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dao;

import java.util.List;

import com.gomap.performance.organisastion.model.EmEmployee;

/**
 * @author krishnakant.bairagi
 *
 */
public interface EmployeeDao {
	public EmEmployee getUserByUserId(String userId) throws Exception;
	public EmEmployee storeEmployeeData(EmEmployee employeeMaster) throws Exception;
	public List<EmEmployee> getEmployeeList(Integer employeeId) throws Exception;
	public EmEmployee updateEmployee(EmEmployee employeeMaster) throws Exception;
	public List<Object> getAllEmplyeeData() throws Exception;
}
