/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dao;

import java.util.List;

import com.gomap.performance.organisastion.model.EmployeePerformanceMaster;
import com.gomap.performance.organisastion.model.EvalutionPeriodMaster;

/**
 * @author Fujitsu
 *
 */
public interface EvaluationDao {
	public EvalutionPeriodMaster createPeriod(EvalutionPeriodMaster evalutionPeriodMaster) throws Exception;
	public EvalutionPeriodMaster updatePeriod(EvalutionPeriodMaster evalutionPeriodMaster) throws Exception;
	
	
	public List<EvalutionPeriodMaster> getPeriod(EvalutionPeriodMaster evalutionPeriodMaster) throws Exception;
	public List<EvalutionPeriodMaster> getPeriodHql(EvalutionPeriodMaster evalutionPeriodMaster) throws Exception;
	public EmployeePerformanceMaster storeEvalution(EmployeePerformanceMaster employeePerformanceMaster) throws Exception;
	public List<EmployeePerformanceMaster> getEvalution(Integer employeeId,Integer evaluterId,Integer durationId,Integer mstId) throws Exception;
	public EmployeePerformanceMaster updateEvalution(EmployeePerformanceMaster employeePerformanceMaster) throws Exception;
	public EmployeePerformanceMaster checkEvalution(Integer employeeId,Integer evaluterId,Integer periodId) throws Exception;
	public List<EvalutionPeriodMaster> getCurrentPeriod() throws Exception;


}
