/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dao;

import java.util.List;

import com.gomap.performance.organisastion.model.EmProject;

/**
 * @author krishnakant.bairagi
 *
 */
public interface ProjectDao {
	public EmProject addProject(EmProject emProject) throws Exception;
	public EmProject updateProject(EmProject emProject) throws Exception;
	public List<EmProject> getProjectList() throws Exception;

}
