/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dao;

import java.util.List;

import com.gomap.performance.organisastion.model.EmTask;

/**
 * @author krishnakant.bairagi
 *
 */
public interface TaskDao {
	public void createTask(EmTask emTask) throws Exception;
	public void updateTask(EmTask emTask)  throws Exception;
	public void deleteTask(EmTask emTask) throws Exception;
	public List<EmTask> getTask(EmTask emTask) throws Exception;

}
