/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dao;

import java.util.List;

import com.gomap.performance.organisastion.model.EmTeam;
import com.gomap.performance.organisastion.model.EmTeamMember;

/**
 * @author krishnakant.bairagi
 *
 */
public interface TeamManagmentDao {
	public void createTeam(EmTeam emTeam) throws Exception;
	public void updateTeam(EmTeam emTeam)  throws Exception;
	public void deleteTeam(EmTeam emTeam) throws Exception;
	public List<EmTeam> getTeam(EmTeam emTeam) throws Exception;
	public void addTeamMember(EmTeamMember emTeamMember) throws Exception;
	public void updateTeamMember(EmTeamMember emTeamMember) throws Exception;
	public List<EmTeamMember> getTeamMember(EmTeamMember emTeamMember) throws Exception;
}
