/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.master.dto;


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * @author krishnakant.bairagi
 *
 */
public class CompanyMasterDto implements Serializable{
	private Integer companyId;
	private String companyName;
	private String adminEmail;
	private String adminMobile;
	private String companyDomain;
	private String portalName;
	private String industryType;
	private String contactPerson;
	private String apiURLPrefix;
	private Integer activateFlag;
	private String companySize;
	/**
	 * @return the companyId
	 */
	/**
	 * @return the companyId
	 */
	public Integer getCompanyId() {
		return companyId;
	}
	/**
	 * @param companyId the companyId to set
	 */
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}
	/**
	 * @return the companyName
	 */
	public String getCompanyName() {
		return companyName;
	}
	/**
	 * @param companyName the companyName to set
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	/**
	 * @return the adminEmail
	 */
	public String getAdminEmail() {
		return adminEmail;
	}
	/**
	 * @param adminEmail the adminEmail to set
	 */
	public void setAdminEmail(String adminEmail) {
		this.adminEmail = adminEmail;
	}
	/**
	 * @return the adminMobile
	 */
	public String getAdminMobile() {
		return adminMobile;
	}
	/**
	 * @param adminMobile the adminMobile to set
	 */
	public void setAdminMobile(String adminMobile) {
		this.adminMobile = adminMobile;
	}
	/**
	 * @return the companyDomain
	 */
	public String getCompanyDomain() {
		return companyDomain;
	}
	/**
	 * @param companyDomain the companyDomain to set
	 */
	public void setCompanyDomain(String companyDomain) {
		this.companyDomain = companyDomain;
	}
	/**
	 * @return the portalName
	 */
	public String getPortalName() {
		return portalName;
	}
	/**
	 * @param portalName the portalName to set
	 */
	public void setPortalName(String portalName) {
		this.portalName = portalName;
	}
	/**
	 * @return the industryType
	 */
	public String getIndustryType() {
		return industryType;
	}
	/**
	 * @param industryType the industryType to set
	 */
	public void setIndustryType(String industryType) {
		this.industryType = industryType;
	}
	/**
	 * @return the contactPerson
	 */
	public String getContactPerson() {
		return contactPerson;
	}
	/**
	 * @param contactPerson the contactPerson to set
	 */
	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}
	/**
	 * @return the apiURLPrefix
	 */
	public String getApiURLPrefix() {
		return apiURLPrefix;
	}
	/**
	 * @param apiURLPrefix the apiURLPrefix to set
	 */
	public void setApiURLPrefix(String apiURLPrefix) {
		this.apiURLPrefix = apiURLPrefix;
	}
	/**
	 * @return the activateFlag
	 */
	public Integer getActivateFlag() {
		return activateFlag;
	}
	/**
	 * @param activateFlag the activateFlag to set
	 */
	public void setActivateFlag(Integer activateFlag) {
		this.activateFlag = activateFlag;
	}
	/**
	 * @return the companySize
	 */
	public String getCompanySize() {
		return companySize;
	}
	/**
	 * @param companySize the companySize to set
	 */
	public void setCompanySize(String companySize) {
		this.companySize = companySize;
	}

}
