/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.master.dto;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.validation.constraints.Size;

import com.sun.istack.internal.NotNull;

/**
 * @author Fujitsu
 *
 */
public class UserDto implements Serializable {
	private Integer userId;
	private String name;
	private String email;
	private String password;
	private Integer emailVerification;
	private String emailToken;
	private String userRole;
	private String companyInfo;
	/**
	 * @return the userId
	 */
	public Integer getUserId() {
		return userId;
	}
	/**
	 * @param userId the userId to set
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}
	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}
	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}
	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}
	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "UserDto [userId=" + userId + ", name=" + name + ", email=" + email + ", password=" + password + "]";
	}
	/**
	 * @return the emailVerification
	 */
	public Integer getEmailVerification() {
		return emailVerification;
	}
	/**
	 * @param emailVerification the emailVerification to set
	 */
	public void setEmailVerification(Integer emailVerification) {
		this.emailVerification = emailVerification;
	}
	/**
	 * @return the emailToken
	 */
	public String getEmailToken() {
		return emailToken;
	}
	/**
	 * @param emailToken the emailToken to set
	 */
	public void setEmailToken(String emailToken) {
		this.emailToken = emailToken;
	}
	/**
	 * @return the companyInfo
	 */
	public String getCompanyInfo() {
		return companyInfo;
	}
	/**
	 * @param companyInfo the companyInfo to set
	 */
	public void setCompanyInfo(String companyInfo) {
		this.companyInfo = companyInfo;
	}
	/**
	 * @return the userRole
	 */
	public String getUserRole() {
		return userRole;
	}
	/**
	 * @param userRole the userRole to set
	 */
	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}


}
