/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.master.controller;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.gomap.performance.master.constant.UrlConstants;
import com.gomap.performance.master.dto.CompanyMasterDto;
import com.gomap.performance.master.dto.ResponseDTO;
import com.gomap.performance.master.service.CompanyService;
import com.gomap.performance.master.util.ResponseWriter;

/**
 * @author krishnakant.bairagi
 *
 */
@RestController
public class CompanyController {
	private static final Logger logger = LoggerFactory.getLogger(CompanyController.class);
	@Autowired
	private CompanyService companyServc;
	
	@RequestMapping(value = {UrlConstants.API_ADD_COMPANY}, method = RequestMethod.POST)
	public @ResponseBody ResponseDTO addCompany(@RequestBody CompanyMasterDto companyMasterDto, BindingResult result) {
		ResponseDTO  responseDTO = null;
		try {  
			if(result.hasErrors()){
				responseDTO = new ResponseDTO();
				responseDTO.setErrorCode(300);
				responseDTO = ResponseWriter.writeResponse(responseDTO);
			} else {
				responseDTO = companyServc.addCompany(companyMasterDto);
				logger.info("here");
			}
		} catch (Exception e) {
			responseDTO = ResponseWriter.writeResponse(e.getCause(), e);
			logger.error("error",e);
		} 
		return responseDTO;
	}
	@RequestMapping(value = {UrlConstants.API_UPDATE_COMPANY}, method = RequestMethod.POST)
	public @ResponseBody ResponseDTO updateCompany(@RequestBody CompanyMasterDto companyMasterDto, BindingResult result) {
		ResponseDTO  responseDTO = null;
		try {  
			if(result.hasErrors()){
				responseDTO = new ResponseDTO();
				responseDTO.setErrorCode(300);
				responseDTO = ResponseWriter.writeResponse(responseDTO);
			} else {
				responseDTO = companyServc.updateCompany(companyMasterDto);
				logger.info("here updateCompany");
			}
		} catch (Exception e) {
			responseDTO = ResponseWriter.writeResponse(e.getCause(), e);
			logger.error("error",e);
		} 
		return responseDTO;
	}

	@RequestMapping(value = {UrlConstants.API_GET_COMPANY}, method = RequestMethod.POST)
	public @ResponseBody ResponseDTO getCompany(@RequestBody CompanyMasterDto companyMasterDto, BindingResult result) {
		ResponseDTO  responseDTO = null;
		try {  
			if(result.hasErrors()){
				responseDTO = new ResponseDTO();
				responseDTO.setErrorCode(300);
				responseDTO = ResponseWriter.writeResponse(responseDTO);
			} else {
				responseDTO = companyServc.getCompanyDetails(companyMasterDto);
				logger.info("here");
			}
		} catch (Exception e) {
			responseDTO = ResponseWriter.writeResponse(e.getCause(), e);
			logger.error("error",e);
		} 
		return responseDTO;
	}

}
