/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dao.impl;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.gomap.performance.organisastion.dao.AuditLogDao;
import com.gomap.performance.organisastion.model.AuditLog;

/**
 * @author Fujitsu
 *
 */
@Repository
public class AuditLogDaoImpl implements AuditLogDao{

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.AuditLogDao#storeAuditLog(com.gomap.performance.organisastion.model.AuditLog)
	 */
	
	@Autowired
	private SessionFactory sessionFactory;
	
	@Override
	public AuditLog storeAuditLog(AuditLog auditLog) {
		// TODO Auto-generated method stub
		this.sessionFactory.getCurrentSession().save(auditLog);
		return auditLog;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.AuditLogDao#getAuditLogData(com.gomap.performance.organisastion.model.AuditLog)
	 */
	@Override
	public List<AuditLog> getAuditLogData(AuditLog auditLog) {
		// TODO Auto-generated method stub
		Criteria criteria=this.sessionFactory.getCurrentSession().createCriteria(AuditLog.class);
		if(auditLog.getCreatedBy()!=null)
		{
			criteria.add(Restrictions.eq("createdBy", auditLog.getCreatedBy()));
				}
		if(auditLog.getCreatedDate()!=null)
		{
			criteria.add(Restrictions.eq("createdDate", auditLog.getCreatedDate()));
				}
		criteria.addOrder(Order.desc("createdDate"));
		return criteria.list();
	}

}
