/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dao.impl;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Restrictions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.gomap.performance.master.constant.AppConstants;
import com.gomap.performance.organisastion.dao.EmployeeDao;
import com.gomap.performance.organisastion.model.EmEmployee;

/**
 * @author krishnakant.bairagi
 *
 */
@Repository
public class EmployeeDaoImpl implements EmployeeDao{

	@Autowired
	private SessionFactory sessionFactory;
	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.EmployeeDao#getUserByUserId(java.lang.String)
	 */
	@Override
	public EmEmployee getUserByUserId(String userId) throws Exception {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.EmployeeDao#storeEmployeeData(com.gomap.performance.organisastion.model.EmployeeMaster)
	 */
	@Override
	public EmEmployee storeEmployeeData(EmEmployee employeeMaster) throws Exception {
		// TODO Auto-generated method stub
		this.sessionFactory.getCurrentSession().save(employeeMaster);
		return employeeMaster;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.EmployeeDao#getEmployeeList(java.lang.Integer)
	 */
	@Override
	public List<EmEmployee> getEmployeeList(Integer employeeId) throws Exception {
		// TODO Auto-generated method stub
		Criteria criteria=this.sessionFactory.getCurrentSession().createCriteria(EmEmployee.class);
		if(employeeId!=null)
		{
			criteria.add(Restrictions.eq("employeeId", employeeId));
		}
		criteria.add(Restrictions.eq("activateFlag", AppConstants.ACTIVE_FLAG));
		return criteria.list();
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.EmployeeDao#updateEmployee(com.gomap.performance.organisastion.model.EmEmployee)
	 */
	@Override
	public EmEmployee updateEmployee(EmEmployee employeeMaster) throws Exception {
		// TODO Auto-generated method stub
		this.sessionFactory.getCurrentSession().update(employeeMaster);
		return employeeMaster;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.EmployeeDao#getEmployeeList(com.gomap.performance.organisastion.model.EmEmployee)
	 */
	

}
