/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dao.impl;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.gomap.performance.master.constant.AppConstants;
import com.gomap.performance.organisastion.dao.ExitInterviewDao;
import com.gomap.performance.organisastion.model.EmDepartment;
import com.gomap.performance.organisastion.model.ExitInterviewEmployeeResponseView;
import com.gomap.performance.organisastion.model.ExitInterviewParam;
import com.gomap.performance.organisastion.model.ExitInterviewParamRlt;
import com.gomap.performance.organisastion.model.ExitInterviewResponse;
import com.gomap.performance.organisastion.model.ExitInterviewResponseMpg;

/**
 * @author Fujitsu
 *
 */
@Repository
public class ExitInterviewDaoImpl implements ExitInterviewDao {

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#addExitInterviewParameter(com.gomap.performance.organisastion.model.ExitInterviewParam)
	 */
	
	@Autowired
	private SessionFactory sessionFactory;
	
	@Override
	public ExitInterviewParam addExitInterviewParameter(ExitInterviewParam exitInterviewParam) throws Exception {
		// TODO Auto-generated method stub
		this.sessionFactory.getCurrentSession().save(exitInterviewParam);
		return exitInterviewParam;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#getExitInterviewParameter(com.gomap.performance.organisastion.model.ExitInterviewParam)
	 */
	@Override
	public List<ExitInterviewParam> getExitInterviewParameter(ExitInterviewParam exitInterviewParam) throws Exception {
		// TODO Auto-generated method stub
		Criteria criteria=this.sessionFactory.getCurrentSession().createCriteria(ExitInterviewParam.class);
		if(exitInterviewParam.getParamName()!=null && !("").equals(exitInterviewParam.getParamName()))
		{
			criteria.add(Restrictions.eq("paramName", exitInterviewParam.getParamName()));
		}
		if(exitInterviewParam.getParamType()!=null)
		{
			criteria.add(Restrictions.eq("paramType", exitInterviewParam.getParamType()));
		}
		if(exitInterviewParam.getParamId()!=null)
		{
			criteria.add(Restrictions.eq("paramId", exitInterviewParam.getParamId()));
		}
		criteria.add(Restrictions.eq("activateFlag", AppConstants.ACTIVE_FLAG));
		//criteria.addOrder(Order.desc("departmentCreatedDate"));
		return criteria.list();
		
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#storeInterviewResponseMpg(com.gomap.performance.organisastion.model.ExitInterviewResponseMpg)
	 */
	@Override
	public ExitInterviewResponseMpg storeInterviewResponseMpg(ExitInterviewResponseMpg interviewResponseMpg)
			throws Exception {
		// TODO Auto-generated method stub
		this.sessionFactory.getCurrentSession().save(interviewResponseMpg);
		
		return interviewResponseMpg;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#storeInterviewResponse(com.gomap.performance.organisastion.model.ExitInterviewResponse)
	 */
	@Override
	public ExitInterviewResponse storeInterviewResponse(ExitInterviewResponse interviewResponse) throws Exception {
		// TODO Auto-generated method stub
		this.sessionFactory.getCurrentSession().save(interviewResponse);
		return interviewResponse;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#getInterviewResponse(com.gomap.performance.organisastion.model.ExitInterviewResponse)
	 */
	@Override
	public ExitInterviewResponse getInterviewResponse(ExitInterviewResponse interviewResponse) throws Exception {
		// TODO Auto-generated method stub
		Criteria crit= this.sessionFactory.getCurrentSession().createCriteria(ExitInterviewResponse.class);
		if(interviewResponse.getResponseId()!=null)
		{
			crit.add(Restrictions.eq("responseId", interviewResponse.getResponseId()));
			
		}
		crit.add(Restrictions.eq("activateFlag", AppConstants.ACTIVE_FLAG));
		return (ExitInterviewResponse) crit.uniqueResult();
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#getInterviewResponseMpg(com.gomap.performance.organisastion.model.ExitInterviewResponseMpg)
	 */
	@Override
	public List<ExitInterviewResponseMpg> getInterviewResponseMpgList(ExitInterviewResponseMpg interviewResponseMpg)
			throws Exception {
		// TODO Auto-generated method stub
		Criteria crit= this.sessionFactory.getCurrentSession().createCriteria(ExitInterviewResponseMpg.class);
		if(interviewResponseMpg.getResponseMpgId()!=null)
		{
			crit.add(Restrictions.eq("responseMpgId", interviewResponseMpg.getResponseMpgId()));
			
		}
		if(interviewResponseMpg.getResponseId()!=null)
		{
			crit.add(Restrictions.eq("responseId", interviewResponseMpg.getResponseId()));
			
		}
		if(interviewResponseMpg.getParamId()!=null)
		{
			crit.add(Restrictions.eq("paramId", interviewResponseMpg.getParamId()));
			
		}
		crit.add(Restrictions.eq("activateFlag", AppConstants.ACTIVE_FLAG));
		crit.addOrder(Order.asc("paramId"));
		return  crit.list();
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#updateInterviewResponse(com.gomap.performance.organisastion.model.ExitInterviewResponse)
	 */
	@Override
	public ExitInterviewResponse updateInterviewResponse(ExitInterviewResponse interviewResponse) throws Exception {
		// TODO Auto-generated method stubget
		this.sessionFactory.getCurrentSession().update(interviewResponse);
		return interviewResponse;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#updateInterviewResponseMpg(com.gomap.performance.organisastion.model.ExitInterviewResponseMpg)
	 */
	@Override
	public ExitInterviewResponseMpg updateInterviewResponseMpg(ExitInterviewResponseMpg interviewResponseMpg)
			throws Exception {
		// TODO Auto-generated method stub
		
		this.sessionFactory.getCurrentSession().update(interviewResponseMpg);
		return interviewResponseMpg;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#getInterviewResponseView()
	 */
	@Override
	public List<ExitInterviewEmployeeResponseView> getInterviewResponseView() throws Exception {
		// TODO Auto-generated method stub
				String empQuery="select new com.gomap.performance.organisastion.model.ExitInterviewEmployeeResponseView("
				+ "dept.departmentId,dept.departmentName,emp.employeeFname,emp.employeeMname,des.designationId"
				+ ",des.designationName,emp.employeeEmail,emp.employeeProfileImg,ext.responseId) from EmEmployee as emp"+
				 ",EmDesignation des" +
		 ",EmDepartment dept,ExitInterviewResponse ext where dept.departmentId=des.departmentId"
		 + " and des.designationId=emp.designationId and emp.activateFlag=1"
		 + " and des.activateFlag=1 and dept.activateFlag=1 and ext.activateFlag=1 and ext.employeeId=emp.employeeId";
	
		List<ExitInterviewEmployeeResponseView> objList=this.sessionFactory.getCurrentSession().createQuery(empQuery).list();
		return objList;
		
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#getInterviewResponseMpg(com.gomap.performance.organisastion.model.ExitInterviewResponseMpg)
	 */
	@Override
	public ExitInterviewResponseMpg getInterviewResponseMpg(ExitInterviewResponseMpg interviewResponseMpg)
			throws Exception {
		Criteria crit= this.sessionFactory.getCurrentSession().createCriteria(ExitInterviewResponseMpg.class);
		if(interviewResponseMpg.getResponseMpgId()!=null)
		{
			crit.add(Restrictions.eq("responseMpgId", interviewResponseMpg.getResponseMpgId()));
			
		}
		if(interviewResponseMpg.getResponseId()!=null)
		{
			crit.add(Restrictions.eq("responseId", interviewResponseMpg.getResponseId()));
			
		}
		crit.add(Restrictions.eq("activateFlag", AppConstants.ACTIVE_FLAG));
		return   (ExitInterviewResponseMpg) crit.uniqueResult();
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#addParamRlt(com.gomap.performance.organisastion.model.ExitInterviewParamRlt)
	 */
	@Override
	public ExitInterviewParamRlt addParamRlt(ExitInterviewParamRlt exitInterviewParamRlt) throws Exception {
		// TODO Auto-generated method stub
		this.sessionFactory.getCurrentSession().save(exitInterviewParamRlt);
		return exitInterviewParamRlt;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#updateParamRlt(com.gomap.performance.organisastion.model.ExitInterviewParamRlt)
	 */
	@Override
	public ExitInterviewParamRlt updateParamRlt(ExitInterviewParamRlt exitInterviewParamRlt) throws Exception {
		// TODO Auto-generated method stub
		this.sessionFactory.getCurrentSession().update(exitInterviewParamRlt);
		return exitInterviewParamRlt;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#getParamRlt(com.gomap.performance.organisastion.model.ExitInterviewParamRlt)
	 */
	@Override
	public List<ExitInterviewParamRlt> getParamRlt(Long paramId,Long paraRltId) throws Exception {
		// TODO Auto-generated method stub
		Criteria crit= this.sessionFactory.getCurrentSession().createCriteria(ExitInterviewParamRlt.class);
		if(paramId!=null)
		{
			crit.add(Restrictions.eq("paramId", paramId));
		}
		if(paraRltId!=null)
		{
			crit.add(Restrictions.eq("paramRltId", paraRltId));
		}
		crit.add(Restrictions.eq("activateFlag", AppConstants.ACTIVE_FLAG));
		//criteria.addOrder(Order.desc("departmentCreatedDate"));
		return crit.list();
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#updateExitInterviewParameter(com.gomap.performance.organisastion.model.ExitInterviewParam)
	 */
	@Override
	public ExitInterviewParam updateExitInterviewParameter(ExitInterviewParam exitInterviewParam) throws Exception {
		// TODO Auto-generated method stub
		this.sessionFactory.getCurrentSession().update(exitInterviewParam);
		return exitInterviewParam;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ExitInterviewDao#getInterviewResponseMpgList(com.gomap.performance.organisastion.model.ExitInterviewResponseMpg)
	 */
	
}
