/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dao.impl;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.gomap.performance.master.constant.AppConstants;
import com.gomap.performance.organisastion.dao.GoalDao;
import com.gomap.performance.organisastion.model.EmGoal;

/**
 * @author krishnakant.bairagi
 *
 */
@Repository
public class GoalDaoImpl implements GoalDao {

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.GoalDao#createGoal(com.gomap.performance.organisastion.model.EmGoal)
	 */
	@Autowired
	private SessionFactory sessionFactory;
	@Override
	public void createGoal(EmGoal emGoal) throws Exception {
		// TODO Auto-generated method stub
		sessionFactory.getCurrentSession().save(emGoal);
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.GoalDao#updateGoal(com.gomap.performance.organisastion.model.EmGoal)
	 */
	@Override
	public void updateGoal(EmGoal emGoal) throws Exception {
		// TODO Auto-generated method stub
	sessionFactory.getCurrentSession().update(emGoal);	
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.GoalDao#deleteGoal(com.gomap.performance.organisastion.model.EmGoal)
	 */
	@Override
	public void deleteGoal(EmGoal emGoal) throws Exception {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.GoalDao#getGoal(com.gomap.performance.organisastion.model.EmGoal)
	 */
	@Override
	public List<EmGoal> getGoal(EmGoal emGoal) throws Exception {
		Criteria criteria=sessionFactory.getCurrentSession().createCriteria(EmGoal.class);
		if(emGoal!=null && emGoal.getTaskId()!=null)
		{
			criteria.add(Restrictions.eq("taskId", emGoal.getTaskId()));
		}
		if(emGoal.getDepartmentId()!=null)
		{
			criteria.add(Restrictions.eq("departmentId", emGoal.getDepartmentId()));
		}
		if(emGoal.getGoalId()!=null)
		{
			criteria.add(Restrictions.eq("goalId", emGoal.getGoalId()));
		}
		if(emGoal.getGoalStartDate()!=null)
		{
			criteria.add(Restrictions.eq("goalStartDate", emGoal.getGoalStartDate()));
		}
		if(emGoal.getGoalApprovedStatus()!=null)
		{
			criteria.add(Restrictions.eq("goalApprovedStatus", emGoal.getGoalApprovedStatus()));
		}
		if(emGoal.getGoalEndDate()!=null)
		{
			criteria.add(Restrictions.eq("goalEndDate", emGoal.getGoalEndDate()));
		}
		criteria.add(Restrictions.eq("activateFlag", AppConstants.ACTIVE_FLAG));
		criteria.addOrder(Order.desc("goalCreatedDate"));
		return criteria.list();
	}

}
