/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dao.impl;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.SessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.gomap.performance.organisastion.dao.ProjectDao;
import com.gomap.performance.organisastion.model.EmProject;

/**
 * @author krishnakant.bairagi
 *
 */
@Repository
public class ProjectDaoImpl implements ProjectDao {

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ProjectDao#addProject(com.gomap.performance.organisastion.model.EmProject)
	 */
	@Autowired
	private SessionFactory sessionFactory;
	@Override
	
	public EmProject addProject(EmProject emProject) throws Exception {
		// TODO Auto-generated method stub
		 this.sessionFactory.getCurrentSession().save(emProject);
		return emProject;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ProjectDao#updateProject(com.gomap.performance.organisastion.model.EmProject)
	 */
	@Override
	
public EmProject updateProject(EmProject emProject) throws Exception {
		// TODO Auto-generated method stub
		this.sessionFactory.getCurrentSession().update(emProject); 
		return emProject;
	}

	/* (non-Javadoc)
	 * @see com.gomap.performance.organisastion.dao.ProjectDao#getProjectList()
	 */
	@Override
	public List<EmProject> getProjectList() throws Exception {
		// TODO Auto-generated method stub
		Criteria crt=this.sessionFactory.getCurrentSession().createCriteria(EmProject.class);
		
		
		return crt.list();
	}

}
