/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.master.model;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author krishnakant.bairagi
 *
 */
@Entity
@Table(name = "company_master")
public class CompanyMaster {
	private Integer companyId;
	private String companyName;
	private String adminEmail;
	private Long adminMobile;
	private String companyDomain;
	private String portalName;
	private String industryType;
	private String contactPerson;
	private String apiURLPrefix;
	private Integer activateFlag;
	private Date createdDate;
	private Date updatedDate;
	private String companySize;
	/**
	 * @return the companyId
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "company_id", nullable = false, precision = 22, scale = 0)
	public Integer getCompanyId() {
		return companyId;
	}
	/**
	 * @param companyId the companyId to set
	 */
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}
	/**
	 * @return the companyName
	 */
	@Column(name = "company_Name", nullable = false, length = 30)
	public String getCompanyName() {
		return companyName;
	}
	/**
	 * @param companyName the companyName to set
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	/**
	 * @return the adminEmail
	 */
	@Column(name = "admin_email", nullable = false, length = 30)
	public String getAdminEmail() {
		return adminEmail;
	}
	/**
	 * @param adminEmail the adminEmail to set
	 */
	
	public void setAdminEmail(String adminEmail) {
		this.adminEmail = adminEmail;
	}
	/**
	 * @return the adminMobile
	 */
	@Column(name = "admin_mobile", nullable = false, length = 30)
	public Long getAdminMobile() {
		return adminMobile;
	}
	/**
	 * @param adminMobile the adminMobile to set
	 */
	
	public void setAdminMobile(Long adminMobile) {
		this.adminMobile = adminMobile;
	}
	/**
	 * @return the companyDomain
	 */
	@Column(name = "company_domain", nullable = false, length = 30)
	public String getCompanyDomain() {
		return companyDomain;
	}
	/**
	 * @param companyDomain the companyDomain to set
	 */
	public void setCompanyDomain(String companyDomain) {
		this.companyDomain = companyDomain;
	}
	/**
	 * @return the portalName
	 */
	@Column(name = "portal_name", nullable = false, length = 30)
	public String getPortalName() {
		return portalName;
	}
	/**
	 * @param portalName the portalName to set
	 */
	public void setPortalName(String portalName) {
		this.portalName = portalName;
	}
	/**
	 * @return the industryType
	 */
	@Column(name = "industry_type", nullable = false, length = 30)
	public String getIndustryType() {
		return industryType;
	}
	/**
	 * @param industryType the industryType to set
	 */
	public void setIndustryType(String industryType) {
		this.industryType = industryType;
	}
	/**
	 * @return the contactPerson
	 */
	@Column(name = "contact_person", nullable = false, length = 30)
	public String getContactPerson() {
		return contactPerson;
	}
	/**
	 * @param contactPerson the contactPerson to set
	 */
	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}
	/**
	 * @return the apiURLPrefix
	 */
	@Column(name = "api_url_prefix", nullable = false, length = 30)
	public String getApiURLPrefix() {
		return apiURLPrefix;
	}
	/**
	 * @param apiURLPrefix the apiURLPrefix to set
	 */
	public void setApiURLPrefix(String apiURLPrefix) {
		this.apiURLPrefix = apiURLPrefix;
	}
	/**
	 * @return the activateFlag
	 */
	@Column(name = "activate_flag", nullable = false, length = 10)
	public Integer getActivateFlag() {
		return activateFlag;
	}
	/**
	 * @param activateFlag the activateFlag to set
	 */
	public void setActivateFlag(Integer activateFlag) {
		this.activateFlag = activateFlag;
	}
	/**
	 * @return the updatedDate
	 */
	@Column(name = "updated_date", nullable = true, length = 20)
	@Temporal(TemporalType.DATE)
	public Date getUpdatedDate() {
		return updatedDate;
	}
	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	/**
	 * @return the createdDate
	 */
	@Column(name = "created_date", nullable = false, length = 20)
	@Temporal(TemporalType.DATE)
	public Date getCreatedDate() {
		return createdDate;
	}
	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	/**
	 * @return the companySize
	 */
	@Column(name = "company_size", nullable = true)
	public String getCompanySize() {
		return companySize;
	}
	/**
	 * @param companySize the companySize to set
	 */
	public void setCompanySize(String companySize) {
		this.companySize = companySize;
	}


}
