/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dto;

import java.util.List;

/**
 * @author Fujitsu
 *
 */

public class DefaultDepartment {
	private List<DepartmentDto> departments;

	/**
	 * @return the departments
	 */
	public List<DepartmentDto> getDepartments() {
		return departments;
	}

	/**
	 * @param departments the departments to set
	 */
	public void setDepartments(List<DepartmentDto> departments) {
		this.departments = departments;
	}

}
