/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dto;

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author krishnakant.bairagi
 *
 */
public class DepartmentDto {
	 /**
	 * @return the departmentId
	 */
	public Integer getDepartmentId() {
		return departmentId;
	}
	/**
	 * @param departmentId the departmentId to set
	 */
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}
	/**
	 * @return the departmentName
	 */
	public String getDepartmentName() {
		return departmentName;
	}
	/**
	 * @param departmentName the departmentName to set
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}
	/**
	 * @return the departmentCreatedDate
	 */
	public Date getDepartmentCreatedDate() {
		return departmentCreatedDate;
	}
	/**
	 * @param departmentCreatedDate the departmentCreatedDate to set
	 */
	public void setDepartmentCreatedDate(Date departmentCreatedDate) {
		this.departmentCreatedDate = departmentCreatedDate;
	}
	/**
	 * @return the departmentUpdatedDate
	 */
	public Date getDepartmentUpdatedDate() {
		return departmentUpdatedDate;
	}
	/**
	 * @param departmentUpdatedDate the departmentUpdatedDate to set
	 */
	public void setDepartmentUpdatedDate(Date departmentUpdatedDate) {
		this.departmentUpdatedDate = departmentUpdatedDate;
	}
	/**
	 * @return the activateFlag
	 */
	public Integer getActivateFlag() {
		return activateFlag;
	}
	/**
	 * @param activateFlag the activateFlag to set
	 */
	public void setActivateFlag(Integer activateFlag) {
		this.activateFlag = activateFlag;
	}
	private Integer departmentId;
	    private String departmentName;
	    private Date departmentCreatedDate;
	    private Date departmentUpdatedDate;
	    private Integer activateFlag;
	   

}
