/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dto;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;

import com.sun.istack.internal.NotNull;

/**
 * @author Fujitsu
 *
 */
public class EmployeePerformanceMasterDto implements Serializable {

	private Integer performaceMstId;
	private Integer performancePeriodId;
	private Integer employeeId;
	private Integer evaluaterId;
	private Integer goalId;
	private Integer taskId;
	private Integer projectId;
	private Integer rating;
	private String comment;
	private Date createdDate;
	private Date updatedDate;
	private Integer activateFlag;
	/**
	 * @return the performaceMstId
	 */
	public Integer getPerformaceMstId() {
		return performaceMstId;
	}
	/**
	 * @param performaceMstId the performaceMstId to set
	 */
	public void setPerformaceMstId(Integer performaceMstId) {
		this.performaceMstId = performaceMstId;
	}
	/**
	 * @return the performancePeriodId
	 */
	public Integer getPerformancePeriodId() {
		return performancePeriodId;
	}
	/**
	 * @param performancePeriodId the performancePeriodId to set
	 */
	public void setPerformancePeriodId(Integer performancePeriodId) {
		this.performancePeriodId = performancePeriodId;
	}
	/**
	 * @return the employeeId
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}
	/**
	 * @param employeeId the employeeId to set
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}
	/**
	 * @return the evaluaterId
	 */
	public Integer getEvaluaterId() {
		return evaluaterId;
	}
	/**
	 * @param evaluaterId the evaluaterId to set
	 */
	public void setEvaluaterId(Integer evaluaterId) {
		this.evaluaterId = evaluaterId;
	}
	/**
	 * @return the goalId
	 */
	public Integer getGoalId() {
		return goalId;
	}
	/**
	 * @param goalId the goalId to set
	 */
	public void setGoalId(Integer goalId) {
		this.goalId = goalId;
	}
	/**
	 * @return the taskId
	 */
	public Integer getTaskId() {
		return taskId;
	}
	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}
	/**
	 * @return the projectId
	 */
	public Integer getProjectId() {
		return projectId;
	}
	/**
	 * @param projectId the projectId to set
	 */
	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}
	/**
	 * @return the rating
	 */
	public Integer getRating() {
		return rating;
	}
	/**
	 * @param rating the rating to set
	 */
	public void setRating(Integer rating) {
		this.rating = rating;
	}
	/**
	 * @return the comment
	 */
	public String getComment() {
		return comment;
	}
	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}
	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}
	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	/**
	 * @return the activateFlag
	 */
	public Integer getActivateFlag() {
		return activateFlag;
	}
	/**
	 * @param activateFlag the activateFlag to set
	 */
	public void setActivateFlag(Integer activateFlag) {
		this.activateFlag = activateFlag;
	}

}
