/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * @author Fujitsu
 *
 */
public class EmployeeElementOperationDto implements Serializable {
	private static final long serialVersionUID = 1L;
	private Integer employeeElementMpgId;
	private Integer employeeElementOperationId;
	private Integer operationId;
	private Date createdDate;

	private Date updatedDate;

	private Integer activateFlag;

	/**
	 * @return the employeeElementMpgId
	 */
	public Integer getEmployeeElementMpgId() {
		return employeeElementMpgId;
	}

	/**
	 * @param employeeElementMpgId the employeeElementMpgId to set
	 */
	public void setEmployeeElementMpgId(Integer employeeElementMpgId) {
		this.employeeElementMpgId = employeeElementMpgId;
	}

	/**
	 * @return the employeeElementOperationId
	 */
	public Integer getEmployeeElementOperationId() {
		return employeeElementOperationId;
	}

	/**
	 * @param employeeElementOperationId the employeeElementOperationId to set
	 */
	public void setEmployeeElementOperationId(Integer employeeElementOperationId) {
		this.employeeElementOperationId = employeeElementOperationId;
	}

	/**
	 * @return the operationId
	 */
	public Integer getOperationId() {
		return operationId;
	}

	/**
	 * @param operationId the operationId to set
	 */
	public void setOperationId(Integer operationId) {
		this.operationId = operationId;
	}

	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the activateFlag
	 */
	public Integer getActivateFlag() {
		return activateFlag;
	}

	/**
	 * @param activateFlag the activateFlag to set
	 */
	public void setActivateFlag(Integer activateFlag) {
		this.activateFlag = activateFlag;
	}
}
