/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dto;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author Fujitsu
 *
 */
public class EvalutionPeriodMasterDto implements Serializable {
	
	
	private Integer performancePeriodId;
	private String periodName;
	
	private Integer createdBy;
	private Date startDate;
	private Date endDate;
	private Date createdDate;
	private Date updatedDate;
	private Integer activateFlag;
	/**
	 * @return the performancePeriodId
	 */
	public Integer getPerformancePeriodId() {
		return performancePeriodId;
	}
	/**
	 * @param performancePeriodId the performancePeriodId to set
	 */
	public void setPerformancePeriodId(Integer performancePeriodId) {
		this.performancePeriodId = performancePeriodId;
	}
	/**
	 * @return the createdBy
	 */
	public Integer getCreatedBy() {
		return createdBy;
	}
	/**
	 * @param createdBy the createdBy to set
	 */
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}
	/**
	 * @return the startDate
	 */
	public Date getStartDate() {
		return startDate;
	}
	/**
	 * @param startDate the startDate to set
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	/**
	 * @return the endDate
	 */
	public Date getEndDate() {
		return endDate;
	}
	/**
	 * @param endDate the endDate to set
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}
	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}
	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	/**
	 * @return the activateFlag
	 */
	public Integer getActivateFlag() {
		return activateFlag;
	}
	/**
	 * @param activateFlag the activateFlag to set
	 */
	public void setActivateFlag(Integer activateFlag) {
		this.activateFlag = activateFlag;
	}
	/**
	 * @return the periodName
	 */
	public String getPeriodName() {
		return periodName;
	}
	/**
	 * @param periodName the periodName to set
	 */
	public void setPeriodName(String periodName) {
		this.periodName = periodName;
	}

}
