/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;

import com.sun.istack.internal.NotNull;

/**
 * @author Fujitsu
 *
 */
public class ExitInterviewResponseMpgDto implements Serializable {
	private Long responseMpgId;
	private Long responseId;
	private Long paramId;
	private Integer rating;
	private Integer paramType;
	private String comment;
	private String paramName;
	private Long paramRltId;
	

	private Date createdDate;
	private Date updatedDate;
	private Integer activateFlag;
	private List<ExitInterviewResponseMpgDto> rlMpgs;
	/**
	 * @return the responseMpgId
	 */
	
	
	public Long getResponseMpgId() {
		return responseMpgId;
	}
	/**
	 * @param responseMpgId the responseMpgId to set
	 */
	public void setResponseMpgId(Long responseMpgId) {
		this.responseMpgId = responseMpgId;
	}
	/**
	 * @return the responseId
	 */
	public Long getResponseId() {
		return responseId;
	}
	/**
	 * @param responseId the responseId to set
	 */
	public void setResponseId(Long responseId) {
		this.responseId = responseId;
	}
	/**
	 * @return the paramId
	 */
	public Long getParamId() {
		return paramId;
	}
	/**
	 * @param paramId the paramId to set
	 */
	public void setParamId(Long paramId) {
		this.paramId = paramId;
	}
	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}
	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}
	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	/**
	 * @return the activateFlag
	 */
	public Integer getActivateFlag() {
		return activateFlag;
	}
	/**
	 * @param activateFlag the activateFlag to set
	 */
	public void setActivateFlag(Integer activateFlag) {
		this.activateFlag = activateFlag;
	}
	/**
	 * @return the rating
	 */
	public Integer getRating() {
		return rating;
	}
	/**
	 * @param rating the rating to set
	 */
	public void setRating(Integer rating) {
		this.rating = rating;
	}
	/**
	 * @return the comment
	 */
	public String getComment() {
		return comment;
	}
	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
	/**
	 * @return the paramName
	 */
	public String getParamName() {
		return paramName;
	}
	/**
	 * @param paramName the paramName to set
	 */
	public void setParamName(String paramName) {
		this.paramName = paramName;
	}
	/**
	 * @return the paramRltId
	 */
	public Long getParamRltId() {
		return paramRltId;
	}
	/**
	 * @param paramRltId the paramRltId to set
	 */
	public void setParamRltId(Long paramRltId) {
		this.paramRltId = paramRltId;
	}
	/**
	 * @return the paramType
	 */
	public Integer getParamType() {
		return paramType;
	}
	/**
	 * @param paramType the paramType to set
	 */
	public void setParamType(Integer paramType) {
		this.paramType = paramType;
	}
	/**
	 * @return the rlMpgs
	 */
	public List<ExitInterviewResponseMpgDto> getRlMpgs() {
		return rlMpgs;
	}
	/**
	 * @param rlMpgs the rlMpgs to set
	 */
	public void setRlMpgs(List<ExitInterviewResponseMpgDto> rlMpgs) {
		this.rlMpgs = rlMpgs;
	}
	

}
