/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dto;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;

import com.sun.istack.internal.NotNull;

/**
 * @author Fujitsu
 *
 */
public class ExitInterviewParamRltDto implements Serializable {
	
    private Long paramRltId;
	
    private Long paramId;
   
    private String paramName;
  
   
    private Date createdDate;
   
    private Date updatedDate;
   
    private Integer activateFlag;
  
    private Integer createdBy;

	/**
	 * @return the paramRltId
	 */
	public Long getParamRltId() {
		return paramRltId;
	}

	/**
	 * @param paramRltId the paramRltId to set
	 */
	public void setParamRltId(Long paramRltId) {
		this.paramRltId = paramRltId;
	}

	/**
	 * @return the paramId
	 */
	public Long getParamId() {
		return paramId;
	}

	/**
	 * @param paramId the paramId to set
	 */
	public void setParamId(Long paramId) {
		this.paramId = paramId;
	}

	/**
	 * @return the paramName
	 */
	public String getParamName() {
		return paramName;
	}

	/**
	 * @param paramName the paramName to set
	 */
	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the activateFlag
	 */
	public Integer getActivateFlag() {
		return activateFlag;
	}

	/**
	 * @param activateFlag the activateFlag to set
	 */
	public void setActivateFlag(Integer activateFlag) {
		this.activateFlag = activateFlag;
	}

	/**
	 * @return the createdBy
	 */
	public Integer getCreatedBy() {
		return createdBy;
	}

	/**
	 * @param createdBy the createdBy to set
	 */
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

}
