/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.organisastion.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;

import com.sun.istack.internal.NotNull;

/**
 * @author Fujitsu
 *
 */
public class ExitInterviewResponseDto implements Serializable {
	private Long responseId;
	 private Integer employeeId;
	private Date createdDate;
	private Date updatedDate;
	private Integer activateFlag;
	private List<ExitInterviewResponseMpgDto> interviewResponseParam;
	/**
	 * @return the responseId
	 */
	public Long getResponseId() {
		return responseId;
	}
	/**
	 * @param responseId the responseId to set
	 */
	public void setResponseId(Long responseId) {
		this.responseId = responseId;
	}
	
	public Date getCreatedDate() {
		return createdDate;
	}
	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}
	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	/**
	 * @return the activateFlag
	 */
	public Integer getActivateFlag() {
		return activateFlag;
	}
	/**
	 * @param activateFlag the activateFlag to set
	 */
	public void setActivateFlag(Integer activateFlag) {
		this.activateFlag = activateFlag;
	}
	/**
	 * @return the interviewResponseParam
	 */
	public List<ExitInterviewResponseMpgDto> getInterviewResponseParam() {
		return interviewResponseParam;
	}
	/**
	 * @param interviewResponseParam the interviewResponseParam to set
	 */
	public void setInterviewResponseParam(List<ExitInterviewResponseMpgDto> interviewResponseParam) {
		this.interviewResponseParam = interviewResponseParam;
	}
	/**
	 * @return the employeeId
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}
	/**
	 * @param employeeId the employeeId to set
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

}
