/**
 * Generated By Krishnakant Bairagi
 */
package com.gomap.performance.master.service.impl;

import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import org.springframework.stereotype.Service;

import com.gomap.performance.master.service.EmailService;

/**
 * @author Fujitsu
 *
 */
@Service
public class EmailServiceImpl implements EmailService{

	/* (non-Javadoc)
	 * @see com.gomap.performance.master.service.EmailService#sendEmail()
	 */
	@Override
	public void sendEmail(String tokenId,String toEmail) {
		// TODO Auto-generated method stub


        // Recipient's email ID needs to be mentioned.
		  // String to = "krishna2491@gmail.com";
		String to=toEmail;
		      // Sender's email ID needs to be mentioned
		      String from = "neeraj.gomap@gmail.com";

        // Assuming you are sending email from through gmails smtp
        String host = "smtp.gmail.com";

        // Get system properties
        Properties properties = System.getProperties();

        // Setup mail server
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "465");
        properties.put("mail.smtp.ssl.enable", "true");
        properties.put("mail.smtp.auth", "true");

        // Get the Session object.// and pass username and password
        Session session = Session.getInstance(properties, new javax.mail.Authenticator() {

            protected PasswordAuthentication getPasswordAuthentication() {

                return new PasswordAuthentication("neeraj.gomap@gmail.com", "neeraj1063");

            }

        });

        // Used to debug SMTP issues
        session.setDebug(true);

        try {
            // Create a default MimeMessage object.
            MimeMessage message = new MimeMessage(session);

            // Set From: header field of the header.
            message.setFrom(new InternetAddress(from));

            // Set To: header field of the header.
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

            // Set Subject: header field
            message.setSubject("Congratulations!! you have registered on E performance");

            // Now set the actual message
            message.setText("http://3.133.244.20:4200/emailverfication?tokenId="+tokenId);

            System.out.println("sending...");
            // Send message
            Transport.send(message);
            System.out.println("Sent message successfully....");
        } catch (MessagingException mex) {
            mex.printStackTrace();
        }

	}

}
